REM === RUBIK'S CUBE SOLVER LIBRARY ===
REM BEGINNER'S LAYER-BY-LAYER METHOD
REM MERGE THIS FILE — REQUIRES lib_rubiks_engine
REM
REM ==========================================
REM  STEP 1: BOTTOM CROSS
REM ==========================================
REM
SolveBottomCross:
  ST$="STEP 1: BOTTOM CROSS": S2$=""
  REM SOLVE 4 BOTTOM EDGES: FRONT, RIGHT, BACK, LEFT
  REM RETRY LOOP HANDLES CASES WHERE INSERTING
  REM THE LAST EDGE DISTURBS AN EARLIER ONE
  PRIVATE RI, XOK
  LOCAL AN, SC, OC
  TC1 = 7: REM MAGENTA (BOTTOM COLOR)
  FOR RI = 1 TO 3
    TC2 = 4: TI = 0: GOSUB SolveBotEdge
    TC2 = 3: TI = 1: GOSUB SolveBotEdge
    TC2 = 5: TI = 2: GOSUB SolveBotEdge
    TC2 = 6: TI = 3: GOSUB SolveBotEdge
    REM CHECK IF ALL 4 SOLVED
    XOK = 1
    IF CL(1,2,0,5)<>7 OR CL(1,2,0,0)<>4 THEN XOK=0
    IF CL(2,2,1,5)<>7 OR CL(2,2,1,2)<>3 THEN XOK=0
    IF CL(1,2,2,5)<>7 OR CL(1,2,2,1)<>5 THEN XOK=0
    IF CL(0,2,1,5)<>7 OR CL(0,2,1,3)<>6 THEN XOK=0
    IF XOK=1 THEN RETURN
  NEXT RI
  RETURN
REM
SolveBotEdge:
  REM SOLVE ONE BOTTOM EDGE
  REM INPUT: TC1, TC2 (TARGET COLORS), TI (TARGET INDEX 0-3)
  PRIVATE AT
  FOR AT = 1 TO 6
    GOSUB FindEdge
    REM ALREADY SOLVED?
    IF EP=TI AND EO=0 THEN RETURN
    REM KICK FROM BOTTOM TO TOP
    IF EP<=3 THEN GOSUB KickBottom
    REM KICK FROM MIDDLE TO TOP
    IF EP>=8 THEN GOSUB KickMiddle
    REM RE-FIND AFTER KICK
    GOSUB FindEdge
    REM ALIGN ABOVE TARGET SLOT
    GOSUB AlignTop
    REM RE-FIND FOR CURRENT ORIENTATION
    GOSUB FindEdge
    REM INSERT BASED ON ORIENTATION
    IF EO=0 THEN GOSUB InsertAligned
    IF EO=1 THEN GOSUB InsertFlipped
    REM CHECK IF SOLVED
    GOSUB FindEdge
    IF EP=TI AND EO=0 THEN RETURN
  NEXT AT
  RETURN
REM
REM ==========================================
REM  EDGE FINDING
REM ==========================================
REM
FindEdge:
  REM SEARCH ALL 12 EDGES FOR TARGET COLORS TC1, TC2
  REM OUTPUT: EP (0-11 POSITION), EO (0=ALIGNED, 1=FLIPPED)
  PRIVATE FA, FB
  REM 0-3: BOTTOM EDGES (FACE-A=F5, FACE-B=SIDE)
  GOSUB FE0: IF EP>=0 THEN RETURN
  GOSUB FE1: IF EP>=0 THEN RETURN
  GOSUB FE2: IF EP>=0 THEN RETURN
  GOSUB FE3: IF EP>=0 THEN RETURN
  REM 4-7: TOP EDGES (FACE-A=F4, FACE-B=SIDE)
  GOSUB FE4: IF EP>=0 THEN RETURN
  GOSUB FE5: IF EP>=0 THEN RETURN
  GOSUB FE6: IF EP>=0 THEN RETURN
  GOSUB FE7: IF EP>=0 THEN RETURN
  REM 8-11: MIDDLE EDGES (SIDE + SIDE)
  GOSUB FE8: IF EP>=0 THEN RETURN
  GOSUB FE9: IF EP>=0 THEN RETURN
  GOSUB FE10: IF EP>=0 THEN RETURN
  GOSUB FE11: IF EP>=0 THEN RETURN
  EP=-1: EO=-1
  RETURN
REM
FE0:
  EP=-1: FA=CL(1,2,0,5): FB=CL(1,2,0,0)
  IF FA=TC1 AND FB=TC2 THEN EP=0: EO=0
  IF FA=TC2 AND FB=TC1 THEN EP=0: EO=1
  RETURN
FE1:
  EP=-1: FA=CL(2,2,1,5): FB=CL(2,2,1,2)
  IF FA=TC1 AND FB=TC2 THEN EP=1: EO=0
  IF FA=TC2 AND FB=TC1 THEN EP=1: EO=1
  RETURN
FE2:
  EP=-1: FA=CL(1,2,2,5): FB=CL(1,2,2,1)
  IF FA=TC1 AND FB=TC2 THEN EP=2: EO=0
  IF FA=TC2 AND FB=TC1 THEN EP=2: EO=1
  RETURN
FE3:
  EP=-1: FA=CL(0,2,1,5): FB=CL(0,2,1,3)
  IF FA=TC1 AND FB=TC2 THEN EP=3: EO=0
  IF FA=TC2 AND FB=TC1 THEN EP=3: EO=1
  RETURN
FE4:
  EP=-1: FA=CL(1,0,0,4): FB=CL(1,0,0,0)
  IF FA=TC1 AND FB=TC2 THEN EP=4: EO=0
  IF FA=TC2 AND FB=TC1 THEN EP=4: EO=1
  RETURN
FE5:
  EP=-1: FA=CL(2,0,1,4): FB=CL(2,0,1,2)
  IF FA=TC1 AND FB=TC2 THEN EP=5: EO=0
  IF FA=TC2 AND FB=TC1 THEN EP=5: EO=1
  RETURN
FE6:
  EP=-1: FA=CL(1,0,2,4): FB=CL(1,0,2,1)
  IF FA=TC1 AND FB=TC2 THEN EP=6: EO=0
  IF FA=TC2 AND FB=TC1 THEN EP=6: EO=1
  RETURN
FE7:
  EP=-1: FA=CL(0,0,1,4): FB=CL(0,0,1,3)
  IF FA=TC1 AND FB=TC2 THEN EP=7: EO=0
  IF FA=TC2 AND FB=TC1 THEN EP=7: EO=1
  RETURN
FE8:
  EP=-1: FA=CL(2,1,0,0): FB=CL(2,1,0,2)
  IF FA=TC1 AND FB=TC2 THEN EP=8: EO=0
  IF FA=TC2 AND FB=TC1 THEN EP=8: EO=1
  RETURN
FE9:
  EP=-1: FA=CL(0,1,0,0): FB=CL(0,1,0,3)
  IF FA=TC1 AND FB=TC2 THEN EP=9: EO=0
  IF FA=TC2 AND FB=TC1 THEN EP=9: EO=1
  RETURN
FE10:
  EP=-1: FA=CL(2,1,2,1): FB=CL(2,1,2,2)
  IF FA=TC1 AND FB=TC2 THEN EP=10: EO=0
  IF FA=TC2 AND FB=TC1 THEN EP=10: EO=1
  RETURN
FE11:
  EP=-1: FA=CL(0,1,2,1): FB=CL(0,1,2,3)
  IF FA=TC1 AND FB=TC2 THEN EP=11: EO=0
  IF FA=TC2 AND FB=TC1 THEN EP=11: EO=1
  RETURN
REM
REM ==========================================
REM  CORNER FINDING
REM ==========================================
REM
FindCorner:
  REM SEARCH ALL 8 CORNERS FOR TARGET COLORS TC1, TC2, TC3
  REM OUTPUT: CP (0-7 POSITION), CO (0-2 ORIENTATION)
  REM CO=0: TC1 ON Y-FACE, CO=1: TC1 ON Z-FACE, CO=2: TC1 ON X-FACE
  PRIVATE FA, FB, FC
  REM 0-3: BOTTOM CORNERS
  GOSUB FC0: IF CP>=0 THEN RETURN
  GOSUB FC1: IF CP>=0 THEN RETURN
  GOSUB FC2: IF CP>=0 THEN RETURN
  GOSUB FC3: IF CP>=0 THEN RETURN
  REM 4-7: TOP CORNERS
  GOSUB FC4: IF CP>=0 THEN RETURN
  GOSUB FC5: IF CP>=0 THEN RETURN
  GOSUB FC6: IF CP>=0 THEN RETURN
  GOSUB FC7: IF CP>=0 THEN RETURN
  CP=-1: CO=-1
  RETURN
REM
FC0:
  REM BFR (2,2,0): F5, F0, F2
  CP=-1: FA=CL(2,2,0,5): FB=CL(2,2,0,0): FC=CL(2,2,0,2)
  IF FA=TC1 AND ((FB=TC2 AND FC=TC3) OR (FB=TC3 AND FC=TC2)) THEN CP=0: CO=0
  IF FB=TC1 AND ((FA=TC2 AND FC=TC3) OR (FA=TC3 AND FC=TC2)) THEN CP=0: CO=1
  IF FC=TC1 AND ((FA=TC2 AND FB=TC3) OR (FA=TC3 AND FB=TC2)) THEN CP=0: CO=2
  RETURN
FC1:
  REM BFL (0,2,0): F5, F0, F3
  CP=-1: FA=CL(0,2,0,5): FB=CL(0,2,0,0): FC=CL(0,2,0,3)
  IF FA=TC1 AND ((FB=TC2 AND FC=TC3) OR (FB=TC3 AND FC=TC2)) THEN CP=1: CO=0
  IF FB=TC1 AND ((FA=TC2 AND FC=TC3) OR (FA=TC3 AND FC=TC2)) THEN CP=1: CO=1
  IF FC=TC1 AND ((FA=TC2 AND FB=TC3) OR (FA=TC3 AND FB=TC2)) THEN CP=1: CO=2
  RETURN
FC2:
  REM BBR (2,2,2): F5, F1, F2
  CP=-1: FA=CL(2,2,2,5): FB=CL(2,2,2,1): FC=CL(2,2,2,2)
  IF FA=TC1 AND ((FB=TC2 AND FC=TC3) OR (FB=TC3 AND FC=TC2)) THEN CP=2: CO=0
  IF FB=TC1 AND ((FA=TC2 AND FC=TC3) OR (FA=TC3 AND FC=TC2)) THEN CP=2: CO=1
  IF FC=TC1 AND ((FA=TC2 AND FB=TC3) OR (FA=TC3 AND FB=TC2)) THEN CP=2: CO=2
  RETURN
FC3:
  REM BBL (0,2,2): F5, F1, F3
  CP=-1: FA=CL(0,2,2,5): FB=CL(0,2,2,1): FC=CL(0,2,2,3)
  IF FA=TC1 AND ((FB=TC2 AND FC=TC3) OR (FB=TC3 AND FC=TC2)) THEN CP=3: CO=0
  IF FB=TC1 AND ((FA=TC2 AND FC=TC3) OR (FA=TC3 AND FC=TC2)) THEN CP=3: CO=1
  IF FC=TC1 AND ((FA=TC2 AND FB=TC3) OR (FA=TC3 AND FB=TC2)) THEN CP=3: CO=2
  RETURN
FC4:
  REM TFR (2,0,0): F4, F0, F2
  CP=-1: FA=CL(2,0,0,4): FB=CL(2,0,0,0): FC=CL(2,0,0,2)
  IF FA=TC1 AND ((FB=TC2 AND FC=TC3) OR (FB=TC3 AND FC=TC2)) THEN CP=4: CO=0
  IF FB=TC1 AND ((FA=TC2 AND FC=TC3) OR (FA=TC3 AND FC=TC2)) THEN CP=4: CO=1
  IF FC=TC1 AND ((FA=TC2 AND FB=TC3) OR (FA=TC3 AND FB=TC2)) THEN CP=4: CO=2
  RETURN
FC5:
  REM TFL (0,0,0): F4, F0, F3
  CP=-1: FA=CL(0,0,0,4): FB=CL(0,0,0,0): FC=CL(0,0,0,3)
  IF FA=TC1 AND ((FB=TC2 AND FC=TC3) OR (FB=TC3 AND FC=TC2)) THEN CP=5: CO=0
  IF FB=TC1 AND ((FA=TC2 AND FC=TC3) OR (FA=TC3 AND FC=TC2)) THEN CP=5: CO=1
  IF FC=TC1 AND ((FA=TC2 AND FB=TC3) OR (FA=TC3 AND FB=TC2)) THEN CP=5: CO=2
  RETURN
FC6:
  REM TBR (2,0,2): F4, F1, F2
  CP=-1: FA=CL(2,0,2,4): FB=CL(2,0,2,1): FC=CL(2,0,2,2)
  IF FA=TC1 AND ((FB=TC2 AND FC=TC3) OR (FB=TC3 AND FC=TC2)) THEN CP=6: CO=0
  IF FB=TC1 AND ((FA=TC2 AND FC=TC3) OR (FA=TC3 AND FC=TC2)) THEN CP=6: CO=1
  IF FC=TC1 AND ((FA=TC2 AND FB=TC3) OR (FA=TC3 AND FB=TC2)) THEN CP=6: CO=2
  RETURN
FC7:
  REM TBL (0,0,2): F4, F1, F3
  CP=-1: FA=CL(0,0,2,4): FB=CL(0,0,2,1): FC=CL(0,0,2,3)
  IF FA=TC1 AND ((FB=TC2 AND FC=TC3) OR (FB=TC3 AND FC=TC2)) THEN CP=7: CO=0
  IF FB=TC1 AND ((FA=TC2 AND FC=TC3) OR (FA=TC3 AND FC=TC2)) THEN CP=7: CO=1
  IF FC=TC1 AND ((FA=TC2 AND FB=TC3) OR (FA=TC3 AND FB=TC2)) THEN CP=7: CO=2
  RETURN
REM
REM ==========================================
REM  KICK TO TOP LAYER
REM ==========================================
REM
KickBottom:
  REM PIECE AT BOTTOM (EP=0..3), KICK TO TOP WITH DOUBLE-TURN
  REM NO PRIVATE VARS — ONLY SETS MS$ FOR DOMOVES
  IF EP=0 THEN MS$="FF": GOSUB DoMoves
  IF EP=1 THEN MS$="RR": GOSUB DoMoves
  IF EP=2 THEN MS$="BB": GOSUB DoMoves
  IF EP=3 THEN MS$="LL": GOSUB DoMoves
  RETURN
REM
KickMiddle:
  REM PIECE AT MIDDLE (EP=8..11), KICK TO TOP
  REM NO PRIVATE VARS — DISPATCHES TO KICKMID HELPERS
  REM CHOOSE FACE TURN THAT DOESN'T DISTURB SOLVED EDGES
  REM EP=8  FRONT-RIGHT: f DISTURBS 0, r DISTURBS 1
  REM EP=9  FRONT-LEFT:  F DISTURBS 0, L DISTURBS 3
  REM EP=10 BACK-RIGHT:  B DISTURBS 2, R DISTURBS 1
  REM EP=11 BACK-LEFT:   b DISTURBS 2, l DISTURBS 3
  IF EP=8 THEN GOSUB KickMid8
  IF EP=9 THEN GOSUB KickMid9
  IF EP=10 THEN GOSUB KickMid10
  IF EP=11 THEN GOSUB KickMid11
  RETURN
REM
KickMid8:
  REM NO PRIVATE VARS — ONLY SETS MS$ FOR DOMOVES
  REM FRONT-RIGHT: f DISTURBS 0, r DISTURBS 1
  REM STUCK WHEN TI>=2 (BOTH 0,1 SOLVED)
  IF TI>=2 THEN MS$="fUF": GOSUB DoMoves: RETURN
  IF TI>=1 THEN MS$="R": GOSUB DoMoves: RETURN
  MS$="f": GOSUB DoMoves
  RETURN
REM
KickMid9:
  REM NO PRIVATE VARS — ONLY SETS MS$ FOR DOMOVES
  REM FRONT-LEFT: F DISTURBS 0, L DISTURBS 3
  REM NEVER STUCK (3 NOT SOLVED BEFORE 0)
  IF TI>=1 THEN MS$="l": GOSUB DoMoves: RETURN
  MS$="F": GOSUB DoMoves
  RETURN
REM
KickMid10:
  REM NO PRIVATE VARS — ONLY SETS MS$ FOR DOMOVES
  REM BACK-RIGHT: B DISTURBS 2, R DISTURBS 1
  REM STUCK WHEN TI>=3 (BOTH 1,2 SOLVED)
  IF TI>=3 THEN MS$="BUb": GOSUB DoMoves: RETURN
  IF TI>=1 THEN MS$="r": GOSUB DoMoves: RETURN
  MS$="B": GOSUB DoMoves
  RETURN
REM
KickMid11:
  REM NO PRIVATE VARS — ONLY SETS MS$ FOR DOMOVES
  REM BACK-LEFT: b DISTURBS 2, l DISTURBS 3
  REM NEVER STUCK (3 NOT SOLVED BEFORE 2)
  IF TI>=3 THEN MS$="L": GOSUB DoMoves: RETURN
  MS$="b": GOSUB DoMoves
  RETURN
REM
REM ==========================================
REM  TOP LAYER ALIGNMENT
REM ==========================================
REM
AlignTop:
  REM ROTATE U TO POSITION EDGE ABOVE TARGET SLOT
  REM TARGET TOP POSITION: TI+4
  REM U CW CYCLE: 4(FRONT)->7(LEFT)->6(BACK)->5(RIGHT)->4
  PRIVATE TP, NU, CP, DP
  TP = TI + 4
  REM FOR FLIPPED EDGES, TARGET ONE U-CCW AHEAD
  REM SO INSERTFLIPPED DOESN'T NEED A LEADING u
  IF EO=1 THEN TP = (TI+1) MOD 4 + 4
  IF EP=TP THEN RETURN
  REM ASSIGN CYCLE POSITIONS: 4=0, 5=3, 6=2, 7=1
  IF EP=4 THEN CP=0
  IF EP=5 THEN CP=3
  IF EP=6 THEN CP=2
  IF EP=7 THEN CP=1
  IF TP=4 THEN DP=0
  IF TP=5 THEN DP=3
  IF TP=6 THEN DP=2
  IF TP=7 THEN DP=1
  NU = (DP - CP + 4) MOD 4
  IF NU=1 THEN MS$="U": GOSUB DoMoves
  IF NU=2 THEN MS$="UU": GOSUB DoMoves
  IF NU=3 THEN MS$="u": GOSUB DoMoves
  RETURN
REM
REM ==========================================
REM  EDGE INSERTION
REM ==========================================
REM
InsertAligned:
  REM NO PRIVATE VARS — ONLY SETS MS$ FOR DOMOVES
  REM EDGE ABOVE TARGET WITH BOTTOM COLOR ON TOP (EO=0)
  REM DOUBLE-TURN TARGET FACE
  IF TI=0 THEN MS$="FF": GOSUB DoMoves
  IF TI=1 THEN MS$="RR": GOSUB DoMoves
  IF TI=2 THEN MS$="BB": GOSUB DoMoves
  IF TI=3 THEN MS$="LL": GOSUB DoMoves
  RETURN
REM
InsertFlipped:
  REM NO PRIVATE VARS — ONLY SETS MS$ FOR DOMOVES
  REM EDGE ABOVE TARGET WITH BOTTOM COLOR ON SIDE (EO=1)
  REM 3-MOVE: u + CW-ADJACENT + TARGET FACE
  IF TI=0 THEN MS$="rF": GOSUB DoMoves
  IF TI=1 THEN MS$="Br": GOSUB DoMoves
  IF TI=2 THEN MS$="lB": GOSUB DoMoves
  IF TI=3 THEN MS$="Fl": GOSUB DoMoves
  RETURN
REM
REM ==========================================
REM  VERIFICATION
REM ==========================================
REM
CheckBottomCross:
  PRIVATE OK
  OK = 1
  IF CL(1,2,0,5)<>7 OR CL(1,2,0,0)<>4 THEN OK=0
  IF CL(2,2,1,5)<>7 OR CL(2,2,1,2)<>3 THEN OK=0
  IF CL(1,2,2,5)<>7 OR CL(1,2,2,1)<>5 THEN OK=0
  IF CL(0,2,1,5)<>7 OR CL(0,2,1,3)<>6 THEN OK=0
  IF OK=1 THEN PRINT "CROSS OK!" ELSE PRINT "CROSS FAIL!": STOP
  RETURN
REM
REM ==========================================
REM  STEP 2: BOTTOM CORNERS
REM ==========================================
REM
SolveBottomCorners:
  PRINT "STEP 2: BOTTOM CORNERS"
  ST$="STEP 2: BOTTOM CORNERS": S2$=""
  PRIVATE RI, XOK
  LOCAL AN, SC, OC
  TC1 = 7
  FOR RI = 1 TO 6
    TC2=4: TC3=3: CI=0: PRINT "  BFR CORNER": S2$="BFR CORNER  ": GOSUB SolveBotCorner
    TC2=4: TC3=6: CI=1: PRINT "  BFL CORNER": S2$="BFL CORNER  ": GOSUB SolveBotCorner
    TC2=5: TC3=3: CI=2: PRINT "  BBR CORNER": S2$="BBR CORNER  ": GOSUB SolveBotCorner
    TC2=5: TC3=6: CI=3: PRINT "  BBL CORNER": S2$="BBL CORNER  ": GOSUB SolveBotCorner
    REM CHECK IF ALL 4 SOLVED
    XOK = 1
    IF CL(2,2,0,5)<>7 OR CL(2,2,0,0)<>4 OR CL(2,2,0,2)<>3 THEN XOK=0
    IF CL(0,2,0,5)<>7 OR CL(0,2,0,0)<>4 OR CL(0,2,0,3)<>6 THEN XOK=0
    IF CL(2,2,2,5)<>7 OR CL(2,2,2,1)<>5 OR CL(2,2,2,2)<>3 THEN XOK=0
    IF CL(0,2,2,5)<>7 OR CL(0,2,2,1)<>5 OR CL(0,2,2,3)<>6 THEN XOK=0
    IF XOK=1 THEN RETURN
  NEXT RI
  RETURN
REM
SolveBotCorner:
  REM SOLVE ONE BOTTOM CORNER
  REM INPUT: TC1, TC2, TC3 (TARGET COLORS), CI (CORNER INDEX 0-3)
  PRIVATE AT
  FOR AT = 1 TO 6
    GOSUB FindCorner
    REM ALREADY SOLVED?
    IF CP=CI AND CO=0 THEN RETURN
    REM EXTRACT FROM BOTTOM IF NEEDED
    IF CP<=3 THEN PRINT "    EXTRACTING": GOSUB ExtractCorner
    REM RE-FIND AFTER EXTRACT
    GOSUB FindCorner
    REM ALIGN ABOVE TARGET SLOT
    PRINT "    ALIGNING"
    GOSUB AlignCornerTop
    REM RE-FIND FOR CURRENT ORIENTATION
    GOSUB FindCorner
    REM INSERT
    PRINT "    INSERTING"
    GOSUB InsertCorner
    REM CHECK IF SOLVED
    GOSUB FindCorner
    IF CP=CI AND CO=0 THEN RETURN
  NEXT AT
  RETURN
REM
REM ==========================================
REM  CORNER EXTRACTION
REM ==========================================
REM
ExtractCorner:
  REM NO PRIVATE VARS — ONLY SETS MS$ FOR DOMOVES
  REM EXTRACT CORNER FROM BOTTOM (CP 0-3) TO TOP
  REM USES CURRENT SLOT'S EXTRACTION ALGORITHM
  IF CP=0 THEN MS$="Rur": GOSUB DoMoves
  IF CP=1 THEN MS$="FUf": GOSUB DoMoves
  IF CP=2 THEN MS$="BUb": GOSUB DoMoves
  IF CP=3 THEN MS$="Lul": GOSUB DoMoves
  RETURN
REM
REM ==========================================
REM  CORNER ALIGNMENT
REM ==========================================
REM
AlignCornerTop:
  REM ROTATE U TO POSITION CORNER ABOVE TARGET SLOT
  REM TARGET TOP POSITION: CI+4
  REM U CW CYCLE: 4(TFR)->5(TFL)->7(TBL)->6(TBR)->4
  PRIVATE TP, NU, CY, DY
  TP = CI + 4
  IF CP=TP THEN RETURN
  REM CYCLE POSITIONS: 4=0, 5=1, 6=3, 7=2
  IF CP=4 THEN CY=0
  IF CP=5 THEN CY=1
  IF CP=6 THEN CY=3
  IF CP=7 THEN CY=2
  IF TP=4 THEN DY=0
  IF TP=5 THEN DY=1
  IF TP=6 THEN DY=3
  IF TP=7 THEN DY=2
  NU = (DY - CY + 4) MOD 4
  IF NU=1 THEN MS$="U": GOSUB DoMoves
  IF NU=2 THEN MS$="UU": GOSUB DoMoves
  IF NU=3 THEN MS$="u": GOSUB DoMoves
  RETURN
REM
REM ==========================================
REM  CORNER INSERTION
REM ==========================================
REM
InsertCorner:
  REM NO PRIVATE VARS — DISPATCHES TO INSERT HELPERS
  REM INSERT CORNER FROM TOP INTO TARGET SLOT
  REM DISPATCH ON CI (TARGET) AND CO (ORIENTATION)
  IF CI=0 THEN GOSUB InsertBFR
  IF CI=1 THEN GOSUB InsertBFL
  IF CI=2 THEN GOSUB InsertBBR
  IF CI=3 THEN GOSUB InsertBBL
  RETURN
REM
InsertBFR:
  REM NO PRIVATE VARS — ONLY SETS MS$ FOR DOMOVES
  REM CO=2 (X-FACE) -> RUr, CO=1 (Z-FACE) -> fuF, CO=0 -> fuF
  IF CO=2 THEN MS$="RUr": GOSUB DoMoves: RETURN
  MS$="fuF": GOSUB DoMoves
  RETURN
REM
InsertBFL:
  REM NO PRIVATE VARS — ONLY SETS MS$ FOR DOMOVES
  REM CO=2 (X-FACE) -> luL, CO=1/0 -> FUf (luL has CO=1 fixed point)
  IF CO=2 THEN MS$="luL": GOSUB DoMoves: RETURN
  MS$="FUf": GOSUB DoMoves
  RETURN
REM
InsertBBR:
  REM NO PRIVATE VARS — ONLY SETS MS$ FOR DOMOVES
  REM CO=1 (Z-FACE) -> BUb, CO=2 (X-FACE) -> ruR, CO=0 -> BUb
  IF CO=2 THEN MS$="ruR": GOSUB DoMoves: RETURN
  MS$="BUb": GOSUB DoMoves
  RETURN
REM
InsertBBL:
  REM NO PRIVATE VARS — ONLY SETS MS$ FOR DOMOVES
  REM CO=2 (X-FACE) -> LUl, CO=1 (Z-FACE) -> buB, CO=0 -> buB
  IF CO=2 THEN MS$="LUl": GOSUB DoMoves: RETURN
  MS$="buB": GOSUB DoMoves
  RETURN
REM
REM ==========================================
REM  CORNER VERIFICATION
REM ==========================================
REM
CheckBottomCorners:
  PRIVATE OK
  OK = 1
  IF CL(2,2,0,5)<>7 OR CL(2,2,0,0)<>4 OR CL(2,2,0,2)<>3 THEN OK=0
  IF CL(0,2,0,5)<>7 OR CL(0,2,0,0)<>4 OR CL(0,2,0,3)<>6 THEN OK=0
  IF CL(2,2,2,5)<>7 OR CL(2,2,2,1)<>5 OR CL(2,2,2,2)<>3 THEN OK=0
  IF CL(0,2,2,5)<>7 OR CL(0,2,2,1)<>5 OR CL(0,2,2,3)<>6 THEN OK=0
  IF OK=1 THEN PRINT "CORNERS OK!" ELSE PRINT "CORNERS FAIL!": STOP
  RETURN
REM
REM ==========================================
REM  STEP 3: MIDDLE LAYER EDGES
REM ==========================================
REM
SolveMiddleEdges:
  PRINT "STEP 3: MIDDLE EDGES"
  ST$="STEP 3: MIDDLE EDGES": S2$=""
  PRIVATE RI, XOK
  LOCAL AN, SC, OC
  FOR RI = 1 TO 6
    TC1=4: TC2=3: EI=0: PRINT "  FR EDGE": S2$="FR EDGE  ": GOSUB SolveMidEdge
    TC1=4: TC2=6: EI=1: PRINT "  FL EDGE": S2$="FL EDGE  ": GOSUB SolveMidEdge
    TC1=5: TC2=3: EI=2: PRINT "  BR EDGE": S2$="BR EDGE  ": GOSUB SolveMidEdge
    TC1=5: TC2=6: EI=3: PRINT "  BL EDGE": S2$="BL EDGE  ": GOSUB SolveMidEdge
    REM CHECK IF ALL 4 SOLVED
    XOK = 1
    IF CL(2,1,0,0)<>4 OR CL(2,1,0,2)<>3 THEN XOK=0
    IF CL(0,1,0,0)<>4 OR CL(0,1,0,3)<>6 THEN XOK=0
    IF CL(2,1,2,1)<>5 OR CL(2,1,2,2)<>3 THEN XOK=0
    IF CL(0,1,2,1)<>5 OR CL(0,1,2,3)<>6 THEN XOK=0
    IF XOK=1 THEN RETURN
  NEXT RI
  RETURN
REM
SolveMidEdge:
  REM SOLVE ONE MIDDLE EDGE
  REM INPUT: TC1, TC2 (TARGET COLORS), EI (EDGE INDEX 0-3)
  PRIVATE AT
  FOR AT = 1 TO 6
    GOSUB FindEdge
    REM ALREADY SOLVED? TARGET EP = EI+8
    IF EP=EI+8 AND EO=0 THEN RETURN
    REM IF IN MIDDLE BUT WRONG, EXTRACT TO TOP
    IF EP>=8 AND EP<=11 THEN PRINT "    EXTRACTING": GOSUB ExtractMidEdge
    REM RE-FIND (NOW IN TOP LAYER)
    GOSUB FindEdge
    REM ALIGN U UNTIL SIDE STICKER MATCHES CENTER
    PRINT "    ALIGNING"
    GOSUB AlignMidEdge
    REM RE-FIND FOR CURRENT POSITION
    GOSUB FindEdge
    REM INSERT
    PRINT "    INSERTING"
    GOSUB InsertMidEdge
    REM CHECK IF SOLVED
    GOSUB FindEdge
    IF EP=EI+8 AND EO=0 THEN RETURN
  NEXT AT
  RETURN
REM
REM ==========================================
REM  MIDDLE EDGE EXTRACTION
REM ==========================================
REM
ExtractMidEdge:
  REM NO PRIVATE VARS — ONLY SETS MS$ FOR DOMOVES
  REM EXTRACT EDGE FROM MIDDLE (EP 8-11) TO TOP
  REM USES ONE OF THE INSERT ALGORITHMS FOR THAT SLOT
  IF EP=8 THEN MS$="URurufUF": GOSUB DoMoves
  IF EP=9 THEN MS$="ulULUFuf": GOSUB DoMoves
  IF EP=10 THEN MS$="urURUBub": GOSUB DoMoves
  IF EP=11 THEN MS$="ULulubUB": GOSUB DoMoves
  RETURN
REM
REM ==========================================
REM  MIDDLE EDGE ALIGNMENT
REM ==========================================
REM
AlignMidEdge:
  REM ROTATE U UNTIL SIDE STICKER MATCHES CENTER
  REM SIDE STICKER COLOR: EO=0 -> TC2, EO=1 -> TC1
  REM SIDE FACE CENTERS: FRONT=4, RIGHT=3, BACK=5, LEFT=6
  PRIVATE SC, TP, NU, CP, DP
  IF EO=0 THEN SC=TC2 ELSE SC=TC1
  REM TARGET EP WHERE SIDE COLOR MATCHES CENTER
  IF SC=4 THEN TP=4
  IF SC=3 THEN TP=5
  IF SC=5 THEN TP=6
  IF SC=6 THEN TP=7
  IF EP=TP THEN RETURN
  REM COMPUTE U TURNS USING EDGE CYCLE
  REM U CW CYCLE: 4(FRONT)->7(LEFT)->6(BACK)->5(RIGHT)->4
  IF EP=4 THEN CP=0
  IF EP=5 THEN CP=3
  IF EP=6 THEN CP=2
  IF EP=7 THEN CP=1
  IF TP=4 THEN DP=0
  IF TP=5 THEN DP=3
  IF TP=6 THEN DP=2
  IF TP=7 THEN DP=1
  NU = (DP - CP + 4) MOD 4
  IF NU=1 THEN MS$="U": GOSUB DoMoves
  IF NU=2 THEN MS$="UU": GOSUB DoMoves
  IF NU=3 THEN MS$="u": GOSUB DoMoves
  RETURN
REM
REM ==========================================
REM  MIDDLE EDGE INSERTION
REM ==========================================
REM
InsertMidEdge:
  REM NO PRIVATE VARS — DISPATCHES ON EI AND EP
  REM EP AFTER ALIGNMENT TELLS US WHICH FACE THE SIDE STICKER IS ON
  REM EP=4: SIDE ON FRONT, EP=5: SIDE ON RIGHT
  REM EP=6: SIDE ON BACK, EP=7: SIDE ON LEFT
  IF EI=0 THEN GOSUB InsertFR
  IF EI=1 THEN GOSUB InsertFL
  IF EI=2 THEN GOSUB InsertBR
  IF EI=3 THEN GOSUB InsertBL
  RETURN
REM
InsertFR:
  REM NO PRIVATE VARS — ONLY SETS MS$ FOR DOMOVES
  REM SIDE ON FRONT (EP=4): INSERT TOWARD RIGHT
  IF EP=4 THEN MS$="URurufUF": GOSUB DoMoves: RETURN
  REM SIDE ON RIGHT (EP=5): INSERT TOWARD FRONT
  MS$="ufUFURur": GOSUB DoMoves
  RETURN
REM
InsertFL:
  REM NO PRIVATE VARS — ONLY SETS MS$ FOR DOMOVES
  REM SIDE ON FRONT (EP=4): INSERT TOWARD LEFT
  IF EP=4 THEN MS$="ulULUFuf": GOSUB DoMoves: RETURN
  REM SIDE ON LEFT (EP=7): INSERT TOWARD FRONT
  MS$="UFufulUL": GOSUB DoMoves
  RETURN
REM
InsertBR:
  REM NO PRIVATE VARS — ONLY SETS MS$ FOR DOMOVES
  REM SIDE ON BACK (EP=6): INSERT TOWARD RIGHT
  IF EP=6 THEN MS$="urURUBub": GOSUB DoMoves: RETURN
  REM SIDE ON RIGHT (EP=5): INSERT TOWARD BACK
  MS$="UBuburUR": GOSUB DoMoves
  RETURN
REM
InsertBL:
  REM NO PRIVATE VARS — ONLY SETS MS$ FOR DOMOVES
  REM SIDE ON BACK (EP=6): INSERT TOWARD LEFT
  IF EP=6 THEN MS$="ULulubUB": GOSUB DoMoves: RETURN
  REM SIDE ON LEFT (EP=7): INSERT TOWARD BACK
  MS$="ubUBULul": GOSUB DoMoves
  RETURN
REM
REM ==========================================
REM  MIDDLE EDGE VERIFICATION
REM ==========================================
REM
CheckMiddleEdges:
  PRIVATE OK
  OK = 1
  IF CL(2,1,0,0)<>4 OR CL(2,1,0,2)<>3 THEN OK=0
  IF CL(0,1,0,0)<>4 OR CL(0,1,0,3)<>6 THEN OK=0
  IF CL(2,1,2,1)<>5 OR CL(2,1,2,2)<>3 THEN OK=0
  IF CL(0,1,2,1)<>5 OR CL(0,1,2,3)<>6 THEN OK=0
  IF OK=1 THEN PRINT "MIDDLE OK!" ELSE PRINT "MIDDLE FAIL!": STOP
  RETURN
REM
REM ==========================================
REM  STEP 4: TOP CROSS (OLL EDGES)
REM ==========================================
REM
SolveTopCross:
  PRINT "STEP 4: TOP CROSS"
  ST$="STEP 4: TOP CROSS": S2$=""
  PRIVATE IT
  LOCAL AN, SC, OC
  FOR IT = 1 TO 4
    REM COUNT YELLOW TOP EDGES
    GOSUB CountTopYellow
    IF YC=4 THEN RETURN
    REM ERROR ON IMPOSSIBLE COUNTS
    IF YC=1 OR YC=3 THEN PRINT "ERROR: YC=";YC: STOP
    REM DOT (YC=0): APPLY DIRECTLY
    IF YC=0 THEN PRINT "  DOT->L": S2$="DOT->L  ": MS$="FRUruf": GOSUB DoMoves: GOTO TopCrossNext
    REM YC=2: DISTINGUISH L-SHAPE FROM LINE
    GOSUB ClassifyTopEdges
    IF TP$="L" THEN GOSUB OrientLShape: PRINT "  L->LINE": S2$="L->LINE  ": MS$="FRUruf": GOSUB DoMoves: GOTO TopCrossNext
    IF TP$="I" THEN GOSUB OrientLine: PRINT "  LINE->CROSS": S2$="LINE->CROSS  ": MS$="FRUruf": GOSUB DoMoves: GOTO TopCrossNext
    TopCrossNext:
  NEXT IT
  PRINT "ERROR: TOP CROSS NOT SOLVED AFTER 4 ITERATIONS": STOP
  RETURN
REM
CountTopYellow:
  REM COUNT HOW MANY TOP EDGES SHOW YELLOW (2)
  REM OUTPUT: YC (0-4)
  YC=0
  IF CL(1,0,0,4)=2 THEN YC=YC+1
  IF CL(2,0,1,4)=2 THEN YC=YC+1
  IF CL(1,0,2,4)=2 THEN YC=YC+1
  IF CL(0,0,1,4)=2 THEN YC=YC+1
  RETURN
REM
ClassifyTopEdges:
  REM CLASSIFY YC=2 PATTERN AS L-SHAPE OR LINE
  REM OUTPUT: TP$ = "L" (ADJACENT) OR "I" (OPPOSITE)
  REM CHECK FOR OPPOSITE PAIRS (LINE)
  IF CL(1,0,0,4)=2 AND CL(1,0,2,4)=2 THEN TP$="I": RETURN
  IF CL(2,0,1,4)=2 AND CL(0,0,1,4)=2 THEN TP$="I": RETURN
  REM OTHERWISE ADJACENT (L-SHAPE)
  TP$="L"
  RETURN
REM
OrientLShape:
  REM ROTATE U UNTIL YELLOW EDGES ARE AT BACK AND LEFT
  PRIVATE J
  FOR J=1 TO 4
    IF CL(1,0,2,4)=2 AND CL(0,0,1,4)=2 THEN RETURN
    MS$="U": GOSUB DoMoves
  NEXT J
  RETURN
REM
OrientLine:
  REM ROTATE U UNTIL YELLOW EDGES ARE AT LEFT AND RIGHT
  PRIVATE J
  FOR J=1 TO 4
    IF CL(2,0,1,4)=2 AND CL(0,0,1,4)=2 THEN RETURN
    MS$="U": GOSUB DoMoves
  NEXT J
  RETURN
REM
REM ==========================================
REM  TOP CROSS VERIFICATION
REM ==========================================
REM
CheckTopCross:
  PRIVATE OK
  OK = 1
  IF CL(1,0,0,4)<>2 THEN OK=0
  IF CL(2,0,1,4)<>2 THEN OK=0
  IF CL(1,0,2,4)<>2 THEN OK=0
  IF CL(0,0,1,4)<>2 THEN OK=0
  IF OK=1 THEN PRINT "TOP CROSS OK!" ELSE PRINT "TOP CROSS FAIL!": STOP
  RETURN
REM
REM ==========================================
REM  STEP 5: TOP EDGE ALIGNMENT (PLL EDGES)
REM ==========================================
REM
SolveTopEdgeAlign:
  PRINT "STEP 5: ALIGN TOP EDGES"
  ST$="STEP 5: ALIGN TOP EDGES": S2$=""
  PRIVATE IT, BM, BN, S0, S1, S2, S3, A0, A1, A2, A3, AM
  LOCAL AN, SC, OC
  FOR IT = 1 TO 6
    REM READ SIDE STICKERS IN CYCLE ORDER: FRONT, LEFT, BACK, RIGHT
    S0 = CL(1,0,0,0)
    S1 = CL(0,0,1,3)
    S2 = CL(1,0,2,1)
    S3 = CL(2,0,1,2)
    REM CHECK IF ANY PURE ROTATION SOLVES IT
    GOSUB FindBestEdgeRotation
    IF BM=4 THEN GOSUB ApplyEdgeRotation: RETURN
    REM FIND BEST PRE-ROTATION FOR ALGORITHM APPLICATION
    REM FOR EACH R, SIMULATE R U TURNS + SWAP(FRONT,LEFT)
    REM THEN FIND BEST POST-ROTATION COUNT
    GOSUB FindBestAlgoRotation
    REM APPLY PRE-ROTATION
    GOSUB ApplyEdgeRotation
    REM APPLY ALGORITHM
    PRINT "  SWAPPING EDGES": S2$="SWAPPING EDGES  "
    MS$="RUrURUUrU": GOSUB DoMoves
  NEXT IT
  PRINT "ERROR: TOP EDGE ALIGN NOT SOLVED AFTER 6 ITERATIONS": STOP
  RETURN
REM
ApplyEdgeRotation:
  REM APPLY BN U TURNS
  IF BN=1 THEN MS$="U": GOSUB DoMoves
  IF BN=2 THEN MS$="UU": GOSUB DoMoves
  IF BN=3 THEN MS$="u": GOSUB DoMoves
  RETURN
REM
FindBestEdgeRotation:
  REM FIND ROTATION (0-3 U TURNS) THAT MAXIMIZES MATCHING EDGES
  REM INPUT: S0-S3 (STICKERS: FRONT, LEFT, BACK, RIGHT)
  REM OUTPUT: BM (BEST MATCH COUNT), BN (BEST ROTATION 0-3)
  REM TARGETS: FRONT=4, LEFT=6, BACK=5, RIGHT=3
  REM U CW CYCLE: FRONT->LEFT->BACK->RIGHT->FRONT
  A0=S0: A1=S1: A2=S2: A3=S3
  GOSUB MaxRotCount
  BM=AM: BN=MN
  RETURN
REM
MaxRotCount:
  REM FIND MAX MATCHES OVER 4 ROTATIONS OF [A0,A1,A2,A3]
  REM TARGETS: FRONT=4, LEFT=6, BACK=5, RIGHT=3
  REM OUTPUT: AM (MAX COUNT), MN (BEST ROTATION 0-3)
  PRIVATE C0, C1, C2, C3
  REM PR=0: FRONT=A0, LEFT=A1, BACK=A2, RIGHT=A3
  C0=0
  IF A0=4 THEN C0=C0+1
  IF A1=6 THEN C0=C0+1
  IF A2=5 THEN C0=C0+1
  IF A3=3 THEN C0=C0+1
  REM PR=1: FRONT=A3, LEFT=A0, BACK=A1, RIGHT=A2
  C1=0
  IF A3=4 THEN C1=C1+1
  IF A0=6 THEN C1=C1+1
  IF A1=5 THEN C1=C1+1
  IF A2=3 THEN C1=C1+1
  REM PR=2: FRONT=A2, LEFT=A3, BACK=A0, RIGHT=A1
  C2=0
  IF A2=4 THEN C2=C2+1
  IF A3=6 THEN C2=C2+1
  IF A0=5 THEN C2=C2+1
  IF A1=3 THEN C2=C2+1
  REM PR=3: FRONT=A1, LEFT=A2, BACK=A3, RIGHT=A0
  C3=0
  IF A1=4 THEN C3=C3+1
  IF A2=6 THEN C3=C3+1
  IF A3=5 THEN C3=C3+1
  IF A0=3 THEN C3=C3+1
  REM PICK MAX
  AM=C0: MN=0
  IF C1>AM THEN AM=C1: MN=1
  IF C2>AM THEN AM=C2: MN=2
  IF C3>AM THEN AM=C3: MN=3
  RETURN
REM
FindBestAlgoRotation:
  REM FOR EACH PRE-ROTATION R (0-3), COMPUTE POST-ALGO STICKERS
  REM ALGO SWAPS FRONT AND LEFT. THEN FIND BEST POST-ROTATION.
  REM INPUT: S0-S3 (CURRENT STICKERS: FRONT, LEFT, BACK, RIGHT)
  REM OUTPUT: BN (BEST PRE-ROTATION), BM (BEST POST-ALGO COUNT)
  REM
  REM POST-ALGO STICKERS FOR EACH PRE-ROTATION:
  REM R=0: SWAP(S0,S1) -> [S1, S0, S2, S3]
  A0=S1: A1=S0: A2=S2: A3=S3
  GOSUB MaxRotCount
  BM=AM: BN=0
  REM R=1: AFTER U, STICKERS=[S3,S0,S1,S2]. SWAP -> [S0, S3, S1, S2]
  A0=S0: A1=S3: A2=S1: A3=S2
  GOSUB MaxRotCount
  IF AM>BM THEN BM=AM: BN=1
  REM R=2: AFTER UU, STICKERS=[S2,S3,S0,S1]. SWAP -> [S3, S2, S0, S1]
  A0=S3: A1=S2: A2=S0: A3=S1
  GOSUB MaxRotCount
  IF AM>BM THEN BM=AM: BN=2
  REM R=3: AFTER U', STICKERS=[S1,S2,S3,S0]. SWAP -> [S2, S1, S3, S0]
  A0=S2: A1=S1: A2=S3: A3=S0
  GOSUB MaxRotCount
  IF AM>BM THEN BM=AM: BN=3
  RETURN
REM
REM ==========================================
REM  TOP EDGE ALIGNMENT VERIFICATION
REM ==========================================
REM
CheckTopEdgeAlign:
  PRIVATE OK
  OK = 1
  IF CL(1,0,0,0)<>4 THEN OK=0
  IF CL(2,0,1,2)<>3 THEN OK=0
  IF CL(1,0,2,1)<>5 THEN OK=0
  IF CL(0,0,1,3)<>6 THEN OK=0
  IF OK=1 THEN PRINT "TOP EDGES OK!" ELSE PRINT "TOP EDGES FAIL!": STOP
  RETURN
REM
REM ==========================================
REM  STEP 6: TOP CORNER POSITIONING (PLL CORNERS)
REM ==========================================
REM
SolveTopCornerPos:
  PRINT "STEP 6: POSITION TOP CORNERS"
  ST$="STEP 6: POSITION TOP CORNERS": S2$=""
  PRIVATE IT, BM, BN
  LOCAL AN, SC, OC
  FOR IT = 1 TO 5
    REM READ CORNER COLOR SETS IN CYCLE ORDER: TFR, TBR, TBL, TFL
    REM U CW CYCLE: TFR->TBR->TBL->TFL->TFR
    REM CYCLE POSITIONS: TFR=0, TFL=3, TBR=1, TBL=2
    REM CHECK IF ANY PURE U ROTATION SOLVES ALL 4
    GOSUB FindBestCornerRotation
    IF BM=4 THEN GOSUB ApplyCornerRotation: RETURN
    REM IF NO ROTATION GIVES ANY CORRECT, APPLY ALGO TO CREATE ONE
    IF BM=0 THEN PRINT "  CYCLING CORNERS": S2$="CYCLING CORNERS  ": MS$="URulUruL": GOSUB DoMoves: GOTO CornerPosNext
    REM ROTATE SO A CORRECT CORNER IS AT TFR (ALGO KEEPS TFR FIXED)
    GOSUB RotateCorrectToTFR
    REM APPLY ALGORITHM (CYCLES TFL->TBL->TBR)
    PRINT "  CYCLING CORNERS": S2$="CYCLING CORNERS  "
    MS$="URulUruL": GOSUB DoMoves
    CornerPosNext:
  NEXT IT
  PRINT "ERROR: TOP CORNER POS NOT SOLVED AFTER 5 ITERATIONS": STOP
  RETURN
REM
ApplyCornerRotation:
  REM APPLY BN U TURNS
  IF BN=1 THEN MS$="U": GOSUB DoMoves
  IF BN=2 THEN MS$="UU": GOSUB DoMoves
  IF BN=3 THEN MS$="u": GOSUB DoMoves
  RETURN
REM
FindBestCornerRotation:
  REM FIND BEST U ROTATION FOR CORNER POSITIONING
  REM U CW CYCLE - TFR(0) TFL(1) TBL(2) TBR(3)
  PRIVATE R, MC, P0, P1, P2, P3
  BM=0: BN=0
  FOR R=0 TO 3
    GOSUB CheckCornerPosAfterR
    IF MC>BM THEN BM=MC: BN=R
  NEXT R
  RETURN
REM
CheckCornerPosAfterR:
  REM COUNT CORRECT CORNERS AFTER R U TURNS
  REM TARGET SUMS - TFR=9 TFL=12 TBL=13 TBR=10
  PRIVATE S0, S1, S2, S3, T0, T1, T2, T3
  REM SUMS AT EACH CYCLE POSITION
  S0=CL(2,0,0,4)+CL(2,0,0,0)+CL(2,0,0,2): REM TFR
  S1=CL(0,0,0,4)+CL(0,0,0,0)+CL(0,0,0,3): REM TFL
  S2=CL(0,0,2,4)+CL(0,0,2,1)+CL(0,0,2,3): REM TBL
  S3=CL(2,0,2,4)+CL(2,0,2,1)+CL(2,0,2,2): REM TBR
  MC=0
  REM SOURCE INDEX FOR EACH TARGET POSITION
  P0=(0-R+4) MOD 4
  P1=(1-R+4) MOD 4
  P2=(2-R+4) MOD 4
  P3=(3-R+4) MOD 4
  REM POS 0 TFR TARGET SUM=9
  IF P0=0 THEN T0=S0
  IF P0=1 THEN T0=S1
  IF P0=2 THEN T0=S2
  IF P0=3 THEN T0=S3
  IF T0=9 THEN MC=MC+1
  REM POS 1 TFL TARGET SUM=12
  IF P1=0 THEN T1=S0
  IF P1=1 THEN T1=S1
  IF P1=2 THEN T1=S2
  IF P1=3 THEN T1=S3
  IF T1=12 THEN MC=MC+1
  REM POS 2 TBL TARGET SUM=13
  IF P2=0 THEN T2=S0
  IF P2=1 THEN T2=S1
  IF P2=2 THEN T2=S2
  IF P2=3 THEN T2=S3
  IF T2=13 THEN MC=MC+1
  REM POS 3 TBR TARGET SUM=10
  IF P3=0 THEN T3=S0
  IF P3=1 THEN T3=S1
  IF P3=2 THEN T3=S2
  IF P3=3 THEN T3=S3
  IF T3=10 THEN MC=MC+1
  RETURN
REM
RotateCorrectToTFR:
  REM ROTATE A CORRECT CORNER TO TFR POSITION
  REM TBR NEEDS 1 U CW, TBL NEEDS 2, TFL NEEDS U'
  PRIVATE S0, S1, S2, S3
  S0=CL(2,0,0,4)+CL(2,0,0,0)+CL(2,0,0,2): REM TFR
  S1=CL(0,0,0,4)+CL(0,0,0,0)+CL(0,0,0,3): REM TFL
  S2=CL(0,0,2,4)+CL(0,0,2,1)+CL(0,0,2,3): REM TBL
  S3=CL(2,0,2,4)+CL(2,0,2,1)+CL(2,0,2,2): REM TBR
  IF S0=9 THEN RETURN
  IF S3=10 THEN MS$="U": GOSUB DoMoves: RETURN
  IF S2=13 THEN MS$="UU": GOSUB DoMoves: RETURN
  IF S1=12 THEN MS$="u": GOSUB DoMoves: RETURN
  RETURN
REM
REM ==========================================
REM  TOP CORNER POSITION VERIFICATION
REM ==========================================
REM
CheckTopCornerPos:
  PRIVATE OK, S0, S1, S2, S3
  OK = 1
  S0=CL(2,0,0,4)+CL(2,0,0,0)+CL(2,0,0,2)
  S1=CL(2,0,2,4)+CL(2,0,2,1)+CL(2,0,2,2)
  S2=CL(0,0,2,4)+CL(0,0,2,1)+CL(0,0,2,3)
  S3=CL(0,0,0,4)+CL(0,0,0,0)+CL(0,0,0,3)
  IF S0<>9 THEN OK=0
  IF S1<>10 THEN OK=0
  IF S2<>13 THEN OK=0
  IF S3<>12 THEN OK=0
  IF OK=1 THEN PRINT "TOP CORNERS POS OK!" ELSE PRINT "TOP CORNERS POS FAIL!": STOP
  RETURN
REM
REM ==========================================
REM  STEP 7: TOP CORNER ORIENTATION
REM ==========================================
REM
SolveTopCornerOrient:
  PRINT "STEP 7: ORIENT TOP CORNERS"
  ST$="STEP 7: ORIENT TOP CORNERS": S2$=""
  PRIVATE IT
  LOCAL AN, SC, OC
  FOR IT = 1 TO 5
    REM CHECK IF ALL 4 CORNERS ORIENTED
    IF CL(2,0,0,4)=2 AND CL(0,0,0,4)=2 AND CL(2,0,2,4)=2 AND CL(0,0,2,4)=2 THEN GOSUB FinalUAlign: RETURN
    REM IF TFR ALREADY ORIENTED, ROTATE AN UNSOLVED CORNER TO TFR
    IF CL(2,0,0,4)=2 THEN GOSUB RotateUnsolvedToTFR
    REM TWIST TFR CORNER USING R'D'RD
    PRINT "  TWISTING CORNER"; IT
    S2$="TWISTING CORNER "+STR$(IT)+"  "
    GOSUB TwistTFR
  NEXT IT
  PRINT "ERROR: TOP CORNER ORIENT NOT SOLVED AFTER 5 ITERATIONS": STOP
  RETURN
REM
RotateUnsolvedToTFR:
  REM FIND FIRST UNSOLVED TOP CORNER AND BRING TO TFR
  REM U CW PIECE CYCLE: TFR->TFL->TBL->TBR->TFR
  REM TFL NEEDS U' (3 CW), TBR NEEDS U (1 CW), TBL NEEDS UU (2 CW)
  IF CL(0,0,0,4)<>2 THEN MS$="u": GOSUB DoMoves: RETURN
  IF CL(2,0,2,4)<>2 THEN MS$="U": GOSUB DoMoves: RETURN
  IF CL(0,0,2,4)<>2 THEN MS$="UU": GOSUB DoMoves: RETURN
  RETURN
REM
TwistTFR:
  REM APPLY R'D'RD UNTIL TFR TOP FACE IS YELLOW
  PRIVATE JT
  FOR JT = 1 TO 6
    MS$="rdRD": GOSUB DoMoves
    IF CL(2,0,0,4)=2 THEN RETURN
  NEXT JT
  PRINT "ERROR: CORNER NOT ORIENTED AFTER 6 RD PAIRS": STOP
  RETURN
REM
FinalUAlign:
  REM ROTATE U UNTIL TOP EDGE SIDE STICKERS MATCH CENTERS
  PRIVATE JT
  FOR JT = 0 TO 3
    IF CL(1,0,0,0)=4 AND CL(2,0,1,2)=3 AND CL(1,0,2,1)=5 AND CL(0,0,1,3)=6 THEN RETURN
    MS$="U": GOSUB DoMoves
  NEXT JT
  PRINT "ERROR: FINAL U ALIGNMENT FAILED": STOP
  RETURN
REM
REM ==========================================
REM  TOP CORNER ORIENTATION VERIFICATION
REM ==========================================
REM
CheckTopCornerOrient:
  PRIVATE OK
  OK = 1
  REM CHECK ALL 4 TOP CORNERS SHOW YELLOW
  IF CL(2,0,0,4)<>2 THEN OK=0
  IF CL(0,0,0,4)<>2 THEN OK=0
  IF CL(2,0,2,4)<>2 THEN OK=0
  IF CL(0,0,2,4)<>2 THEN OK=0
  REM CHECK TOP EDGE ALIGNMENT (FINAL U)
  IF CL(1,0,0,0)<>4 THEN OK=0
  IF CL(2,0,1,2)<>3 THEN OK=0
  IF CL(1,0,2,1)<>5 THEN OK=0
  IF CL(0,0,1,3)<>6 THEN OK=0
  IF OK=1 THEN PRINT "TOP CORNERS ORIENT OK!" ELSE PRINT "TOP CORNERS ORIENT FAIL!": STOP
  RETURN
REM
REM ==========================================
REM  FULL SOLVE VERIFICATION (ALL 54 STICKERS)
REM ==========================================
REM
CheckFullSolve:
  PRIVATE OK, IX, IY, IZ
  OK = 1
  REM FRONT (F=0, IZ=0) = RED (4), BACK (F=1, IZ=2) = BUFF (5)
  FOR IX=0 TO 2: FOR IY=0 TO 2
    IF CL(IX,IY,0,0)<>4 THEN OK=0
    IF CL(IX,IY,2,1)<>5 THEN OK=0
  NEXT IY: NEXT IX
  REM RIGHT (F=2, IX=2) = BLUE (3), LEFT (F=3, IX=0) = CYAN (6)
  FOR IY=0 TO 2: FOR IZ=0 TO 2
    IF CL(2,IY,IZ,2)<>3 THEN OK=0
    IF CL(0,IY,IZ,3)<>6 THEN OK=0
  NEXT IZ: NEXT IY
  REM TOP (F=4, IY=0) = YELLOW (2), BOTTOM (F=5, IY=2) = MAGENTA (7)
  FOR IX=0 TO 2: FOR IZ=0 TO 2
    IF CL(IX,0,IZ,4)<>2 THEN OK=0
    IF CL(IX,2,IZ,5)<>7 THEN OK=0
  NEXT IZ: NEXT IX
  IF OK=1 THEN PRINT "FULL SOLVE OK!" ELSE PRINT "FULL SOLVE FAIL!": STOP
  RETURN
REM
REM ==========================================
REM  CUBE COLOR COUNT INTEGRITY CHECK
REM ==========================================
REM
CheckCubeIntegrity:
  REM VERIFY EACH COLOR APPEARS EXACTLY 9 TIMES
  REM ACROSS ALL 54 VISIBLE STICKERS
  PRIVATE IX, IY, IZ, OK
  C2=0: C3=0: C4=0: C5=0: C6=0: C7=0
  REM FRONT (F=0, IZ=0) AND BACK (F=1, IZ=2)
  FOR IX=0 TO 2: FOR IY=0 TO 2
    GOSUB CCI1
  NEXT IY: NEXT IX
  REM RIGHT (F=2, IX=2) AND LEFT (F=3, IX=0)
  FOR IY=0 TO 2: FOR IZ=0 TO 2
    GOSUB CCI2
  NEXT IZ: NEXT IY
  REM TOP (F=4, IY=0) AND BOTTOM (F=5, IY=2)
  FOR IX=0 TO 2: FOR IZ=0 TO 2
    GOSUB CCI3
  NEXT IZ: NEXT IX
  OK=1
  IF C2<>9 THEN PRINT "INTEGRITY: YELLOW=";C2;" EXPECTED 9": OK=0
  IF C3<>9 THEN PRINT "INTEGRITY: BLUE=";C3;" EXPECTED 9": OK=0
  IF C4<>9 THEN PRINT "INTEGRITY: RED=";C4;" EXPECTED 9": OK=0
  IF C5<>9 THEN PRINT "INTEGRITY: BUFF=";C5;" EXPECTED 9": OK=0
  IF C6<>9 THEN PRINT "INTEGRITY: CYAN=";C6;" EXPECTED 9": OK=0
  IF C7<>9 THEN PRINT "INTEGRITY: MAGENTA=";C7;" EXPECTED 9": OK=0
  IF OK=1 THEN PRINT "INTEGRITY OK!" ELSE PRINT "CUBE INTEGRITY FAIL!": STOP
  RETURN
REM
CCI1:
  REM COUNT FRONT AND BACK STICKERS
  PRIVATE V
  V=CL(IX,IY,0,0): GOSUB CCCount
  V=CL(IX,IY,2,1): GOSUB CCCount
  RETURN
CCI2:
  REM COUNT RIGHT AND LEFT STICKERS
  PRIVATE V
  V=CL(2,IY,IZ,2): GOSUB CCCount
  V=CL(0,IY,IZ,3): GOSUB CCCount
  RETURN
CCI3:
  REM COUNT TOP AND BOTTOM STICKERS
  PRIVATE V
  V=CL(IX,0,IZ,4): GOSUB CCCount
  V=CL(IX,2,IZ,5): GOSUB CCCount
  RETURN
CCCount:
  IF V=2 THEN C2=C2+1
  IF V=3 THEN C3=C3+1
  IF V=4 THEN C4=C4+1
  IF V=5 THEN C5=C5+1
  IF V=6 THEN C6=C6+1
  IF V=7 THEN C7=C7+1
  RETURN
