REM === RUBIK'S CUBE SOLVER LIBRARY ===
REM BEGINNER'S LAYER-BY-LAYER METHOD
REM MERGE THIS FILE — REQUIRES lib_rubiks_engine
REM
REM ==========================================
REM  STEP 1: BOTTOM CROSS
REM ==========================================
REM
SolveBottomCross:
ST$="STEP 1: BOTTOM CROSS": S2$=""
REM SOLVE 4 BOTTOM EDGES: FRONT, RIGHT, BACK, LEFT
REM RETRY LOOP HANDLES CASES WHERE INSERTING
REM THE LAST EDGE DISTURBS AN EARLIER ONE
LOCAL RI, XOK
TC1 = 7: REM MAGENTA (BOTTOM COLOR)
FOR RI = 1 TO 3
  TC2 = 4: TI = 0: GOSUB SolveBotEdge
  TC2 = 3: TI = 1: GOSUB SolveBotEdge
  TC2 = 5: TI = 2: GOSUB SolveBotEdge
  TC2 = 6: TI = 3: GOSUB SolveBotEdge
  REM CHECK IF ALL 4 SOLVED
  XOK = 1
  IF CL(1,2,0,5)<>7 OR CL(1,2,0,0)<>4 THEN XOK=0
  IF CL(2,2,1,5)<>7 OR CL(2,2,1,2)<>3 THEN XOK=0
  IF CL(1,2,2,5)<>7 OR CL(1,2,2,1)<>5 THEN XOK=0
  IF CL(0,2,1,5)<>7 OR CL(0,2,1,3)<>6 THEN XOK=0
  IF XOK=1 THEN RETURN
NEXT RI
RETURN
REM
SolveBotEdge:
REM SOLVE ONE BOTTOM EDGE
REM INPUT: TC1, TC2 (TARGET COLORS), TI (TARGET INDEX 0-3)
LOCAL AT
FOR AT = 1 TO 6
  GOSUB FindEdge
  REM ALREADY SOLVED?
  IF EP=TI AND EO=0 THEN RETURN
  REM KICK FROM BOTTOM TO TOP
  IF EP<=3 THEN GOSUB KickBottom
  REM KICK FROM MIDDLE TO TOP
  IF EP>=8 THEN GOSUB KickMiddle
  REM RE-FIND AFTER KICK
  GOSUB FindEdge
  REM ALIGN ABOVE TARGET SLOT
  GOSUB AlignTop
  REM RE-FIND FOR CURRENT ORIENTATION
  GOSUB FindEdge
  REM INSERT BASED ON ORIENTATION
  IF EO=0 THEN GOSUB InsertAligned
  IF EO=1 THEN GOSUB InsertFlipped
  REM CHECK IF SOLVED
  GOSUB FindEdge
  IF EP=TI AND EO=0 THEN RETURN
NEXT AT
RETURN
REM
REM ==========================================
REM  EDGE FINDING
REM ==========================================
REM
FindEdge:
REM SEARCH ALL 12 EDGES FOR TARGET COLORS TC1, TC2
REM OUTPUT: EP (0-11 POSITION), EO (0=ALIGNED, 1=FLIPPED)
LOCAL FA, FB
REM 0-3: BOTTOM EDGES (FACE-A=F5, FACE-B=SIDE)
GOSUB FE0: IF EP>=0 THEN RETURN
GOSUB FE1: IF EP>=0 THEN RETURN
GOSUB FE2: IF EP>=0 THEN RETURN
GOSUB FE3: IF EP>=0 THEN RETURN
REM 4-7: TOP EDGES (FACE-A=F4, FACE-B=SIDE)
GOSUB FE4: IF EP>=0 THEN RETURN
GOSUB FE5: IF EP>=0 THEN RETURN
GOSUB FE6: IF EP>=0 THEN RETURN
GOSUB FE7: IF EP>=0 THEN RETURN
REM 8-11: MIDDLE EDGES (SIDE + SIDE)
GOSUB FE8: IF EP>=0 THEN RETURN
GOSUB FE9: IF EP>=0 THEN RETURN
GOSUB FE10: IF EP>=0 THEN RETURN
GOSUB FE11: IF EP>=0 THEN RETURN
EP=-1: EO=-1
RETURN
REM
FE0:
EP=-1: FA=CL(1,2,0,5): FB=CL(1,2,0,0)
IF FA=TC1 AND FB=TC2 THEN EP=0: EO=0
IF FA=TC2 AND FB=TC1 THEN EP=0: EO=1
RETURN
FE1:
EP=-1: FA=CL(2,2,1,5): FB=CL(2,2,1,2)
IF FA=TC1 AND FB=TC2 THEN EP=1: EO=0
IF FA=TC2 AND FB=TC1 THEN EP=1: EO=1
RETURN
FE2:
EP=-1: FA=CL(1,2,2,5): FB=CL(1,2,2,1)
IF FA=TC1 AND FB=TC2 THEN EP=2: EO=0
IF FA=TC2 AND FB=TC1 THEN EP=2: EO=1
RETURN
FE3:
EP=-1: FA=CL(0,2,1,5): FB=CL(0,2,1,3)
IF FA=TC1 AND FB=TC2 THEN EP=3: EO=0
IF FA=TC2 AND FB=TC1 THEN EP=3: EO=1
RETURN
FE4:
EP=-1: FA=CL(1,0,0,4): FB=CL(1,0,0,0)
IF FA=TC1 AND FB=TC2 THEN EP=4: EO=0
IF FA=TC2 AND FB=TC1 THEN EP=4: EO=1
RETURN
FE5:
EP=-1: FA=CL(2,0,1,4): FB=CL(2,0,1,2)
IF FA=TC1 AND FB=TC2 THEN EP=5: EO=0
IF FA=TC2 AND FB=TC1 THEN EP=5: EO=1
RETURN
FE6:
EP=-1: FA=CL(1,0,2,4): FB=CL(1,0,2,1)
IF FA=TC1 AND FB=TC2 THEN EP=6: EO=0
IF FA=TC2 AND FB=TC1 THEN EP=6: EO=1
RETURN
FE7:
EP=-1: FA=CL(0,0,1,4): FB=CL(0,0,1,3)
IF FA=TC1 AND FB=TC2 THEN EP=7: EO=0
IF FA=TC2 AND FB=TC1 THEN EP=7: EO=1
RETURN
FE8:
EP=-1: FA=CL(2,1,0,0): FB=CL(2,1,0,2)
IF FA=TC1 AND FB=TC2 THEN EP=8: EO=0
IF FA=TC2 AND FB=TC1 THEN EP=8: EO=1
RETURN
FE9:
EP=-1: FA=CL(0,1,0,0): FB=CL(0,1,0,3)
IF FA=TC1 AND FB=TC2 THEN EP=9: EO=0
IF FA=TC2 AND FB=TC1 THEN EP=9: EO=1
RETURN
FE10:
EP=-1: FA=CL(2,1,2,1): FB=CL(2,1,2,2)
IF FA=TC1 AND FB=TC2 THEN EP=10: EO=0
IF FA=TC2 AND FB=TC1 THEN EP=10: EO=1
RETURN
FE11:
EP=-1: FA=CL(0,1,2,1): FB=CL(0,1,2,3)
IF FA=TC1 AND FB=TC2 THEN EP=11: EO=0
IF FA=TC2 AND FB=TC1 THEN EP=11: EO=1
RETURN
REM
REM ==========================================
REM  CORNER FINDING
REM ==========================================
REM
FindCorner:
REM SEARCH ALL 8 CORNERS FOR TARGET COLORS TC1, TC2, TC3
REM OUTPUT: CP (0-7 POSITION), CO (0-2 ORIENTATION)
REM CO=0: TC1 ON Y-FACE, CO=1: TC1 ON Z-FACE, CO=2: TC1 ON X-FACE
LOCAL FA, FB, FC
REM 0-3: BOTTOM CORNERS
GOSUB FC0: IF CP>=0 THEN RETURN
GOSUB FC1: IF CP>=0 THEN RETURN
GOSUB FC2: IF CP>=0 THEN RETURN
GOSUB FC3: IF CP>=0 THEN RETURN
REM 4-7: TOP CORNERS
GOSUB FC4: IF CP>=0 THEN RETURN
GOSUB FC5: IF CP>=0 THEN RETURN
GOSUB FC6: IF CP>=0 THEN RETURN
GOSUB FC7: IF CP>=0 THEN RETURN
CP=-1: CO=-1
RETURN
REM
FC0:
REM BFR (2,2,0): F5, F0, F2
CP=-1: FA=CL(2,2,0,5): FB=CL(2,2,0,0): FC=CL(2,2,0,2)
IF FA=TC1 AND ((FB=TC2 AND FC=TC3) OR (FB=TC3 AND FC=TC2)) THEN CP=0: CO=0
IF FB=TC1 AND ((FA=TC2 AND FC=TC3) OR (FA=TC3 AND FC=TC2)) THEN CP=0: CO=1
IF FC=TC1 AND ((FA=TC2 AND FB=TC3) OR (FA=TC3 AND FB=TC2)) THEN CP=0: CO=2
RETURN
FC1:
REM BFL (0,2,0): F5, F0, F3
CP=-1: FA=CL(0,2,0,5): FB=CL(0,2,0,0): FC=CL(0,2,0,3)
IF FA=TC1 AND ((FB=TC2 AND FC=TC3) OR (FB=TC3 AND FC=TC2)) THEN CP=1: CO=0
IF FB=TC1 AND ((FA=TC2 AND FC=TC3) OR (FA=TC3 AND FC=TC2)) THEN CP=1: CO=1
IF FC=TC1 AND ((FA=TC2 AND FB=TC3) OR (FA=TC3 AND FB=TC2)) THEN CP=1: CO=2
RETURN
FC2:
REM BBR (2,2,2): F5, F1, F2
CP=-1: FA=CL(2,2,2,5): FB=CL(2,2,2,1): FC=CL(2,2,2,2)
IF FA=TC1 AND ((FB=TC2 AND FC=TC3) OR (FB=TC3 AND FC=TC2)) THEN CP=2: CO=0
IF FB=TC1 AND ((FA=TC2 AND FC=TC3) OR (FA=TC3 AND FC=TC2)) THEN CP=2: CO=1
IF FC=TC1 AND ((FA=TC2 AND FB=TC3) OR (FA=TC3 AND FB=TC2)) THEN CP=2: CO=2
RETURN
FC3:
REM BBL (0,2,2): F5, F1, F3
CP=-1: FA=CL(0,2,2,5): FB=CL(0,2,2,1): FC=CL(0,2,2,3)
IF FA=TC1 AND ((FB=TC2 AND FC=TC3) OR (FB=TC3 AND FC=TC2)) THEN CP=3: CO=0
IF FB=TC1 AND ((FA=TC2 AND FC=TC3) OR (FA=TC3 AND FC=TC2)) THEN CP=3: CO=1
IF FC=TC1 AND ((FA=TC2 AND FB=TC3) OR (FA=TC3 AND FB=TC2)) THEN CP=3: CO=2
RETURN
FC4:
REM TFR (2,0,0): F4, F0, F2
CP=-1: FA=CL(2,0,0,4): FB=CL(2,0,0,0): FC=CL(2,0,0,2)
IF FA=TC1 AND ((FB=TC2 AND FC=TC3) OR (FB=TC3 AND FC=TC2)) THEN CP=4: CO=0
IF FB=TC1 AND ((FA=TC2 AND FC=TC3) OR (FA=TC3 AND FC=TC2)) THEN CP=4: CO=1
IF FC=TC1 AND ((FA=TC2 AND FB=TC3) OR (FA=TC3 AND FB=TC2)) THEN CP=4: CO=2
RETURN
FC5:
REM TFL (0,0,0): F4, F0, F3
CP=-1: FA=CL(0,0,0,4): FB=CL(0,0,0,0): FC=CL(0,0,0,3)
IF FA=TC1 AND ((FB=TC2 AND FC=TC3) OR (FB=TC3 AND FC=TC2)) THEN CP=5: CO=0
IF FB=TC1 AND ((FA=TC2 AND FC=TC3) OR (FA=TC3 AND FC=TC2)) THEN CP=5: CO=1
IF FC=TC1 AND ((FA=TC2 AND FB=TC3) OR (FA=TC3 AND FB=TC2)) THEN CP=5: CO=2
RETURN
FC6:
REM TBR (2,0,2): F4, F1, F2
CP=-1: FA=CL(2,0,2,4): FB=CL(2,0,2,1): FC=CL(2,0,2,2)
IF FA=TC1 AND ((FB=TC2 AND FC=TC3) OR (FB=TC3 AND FC=TC2)) THEN CP=6: CO=0
IF FB=TC1 AND ((FA=TC2 AND FC=TC3) OR (FA=TC3 AND FC=TC2)) THEN CP=6: CO=1
IF FC=TC1 AND ((FA=TC2 AND FB=TC3) OR (FA=TC3 AND FB=TC2)) THEN CP=6: CO=2
RETURN
FC7:
REM TBL (0,0,2): F4, F1, F3
CP=-1: FA=CL(0,0,2,4): FB=CL(0,0,2,1): FC=CL(0,0,2,3)
IF FA=TC1 AND ((FB=TC2 AND FC=TC3) OR (FB=TC3 AND FC=TC2)) THEN CP=7: CO=0
IF FB=TC1 AND ((FA=TC2 AND FC=TC3) OR (FA=TC3 AND FC=TC2)) THEN CP=7: CO=1
IF FC=TC1 AND ((FA=TC2 AND FB=TC3) OR (FA=TC3 AND FB=TC2)) THEN CP=7: CO=2
RETURN
REM
REM ==========================================
REM  KICK TO TOP LAYER
REM ==========================================
REM
KickBottom:
REM PIECE AT BOTTOM (EP=0..3), KICK TO TOP WITH DOUBLE-TURN
REM NO LOCAL VARS — ONLY SETS MS$ FOR DOMOVES
IF EP=0 THEN MS$="FF": GOSUB DoMoves
IF EP=1 THEN MS$="RR": GOSUB DoMoves
IF EP=2 THEN MS$="BB": GOSUB DoMoves
IF EP=3 THEN MS$="LL": GOSUB DoMoves
RETURN
REM
KickMiddle:
REM PIECE AT MIDDLE (EP=8..11), KICK TO TOP
REM NO LOCAL VARS — DISPATCHES TO KICKMID HELPERS
REM CHOOSE FACE TURN THAT DOESN'T DISTURB SOLVED EDGES
REM EP=8  FRONT-RIGHT: f DISTURBS 0, r DISTURBS 1
REM EP=9  FRONT-LEFT:  F DISTURBS 0, L DISTURBS 3
REM EP=10 BACK-RIGHT:  B DISTURBS 2, R DISTURBS 1
REM EP=11 BACK-LEFT:   b DISTURBS 2, l DISTURBS 3
IF EP=8 THEN GOSUB KickMid8
IF EP=9 THEN GOSUB KickMid9
IF EP=10 THEN GOSUB KickMid10
IF EP=11 THEN GOSUB KickMid11
RETURN
REM
KickMid8:
REM NO LOCAL VARS — ONLY SETS MS$ FOR DOMOVES
REM FRONT-RIGHT: f DISTURBS 0, r DISTURBS 1
REM STUCK WHEN TI>=2 (BOTH 0,1 SOLVED)
IF TI>=2 THEN MS$="fUF": GOSUB DoMoves: RETURN
IF TI>=1 THEN MS$="R": GOSUB DoMoves: RETURN
MS$="f": GOSUB DoMoves
RETURN
REM
KickMid9:
REM NO LOCAL VARS — ONLY SETS MS$ FOR DOMOVES
REM FRONT-LEFT: F DISTURBS 0, L DISTURBS 3
REM NEVER STUCK (3 NOT SOLVED BEFORE 0)
IF TI>=1 THEN MS$="l": GOSUB DoMoves: RETURN
MS$="F": GOSUB DoMoves
RETURN
REM
KickMid10:
REM NO LOCAL VARS — ONLY SETS MS$ FOR DOMOVES
REM BACK-RIGHT: B DISTURBS 2, R DISTURBS 1
REM STUCK WHEN TI>=3 (BOTH 1,2 SOLVED)
IF TI>=3 THEN MS$="BUb": GOSUB DoMoves: RETURN
IF TI>=1 THEN MS$="r": GOSUB DoMoves: RETURN
MS$="B": GOSUB DoMoves
RETURN
REM
KickMid11:
REM NO LOCAL VARS — ONLY SETS MS$ FOR DOMOVES
REM BACK-LEFT: b DISTURBS 2, l DISTURBS 3
REM NEVER STUCK (3 NOT SOLVED BEFORE 2)
IF TI>=3 THEN MS$="L": GOSUB DoMoves: RETURN
MS$="b": GOSUB DoMoves
RETURN
REM
REM ==========================================
REM  TOP LAYER ALIGNMENT
REM ==========================================
REM
AlignTop:
REM ROTATE U TO POSITION EDGE ABOVE TARGET SLOT
REM TARGET TOP POSITION: TI+4
REM U CW CYCLE: 4(FRONT)->7(LEFT)->6(BACK)->5(RIGHT)->4
LOCAL TP, NU, CP, DP
TP = TI + 4
REM FOR FLIPPED EDGES, TARGET ONE U-CCW AHEAD
REM SO INSERTFLIPPED DOESN'T NEED A LEADING u
IF EO=1 THEN TP = (TI+1) MOD 4 + 4
IF EP=TP THEN RETURN
REM ASSIGN CYCLE POSITIONS: 4=0, 5=3, 6=2, 7=1
IF EP=4 THEN CP=0
IF EP=5 THEN CP=3
IF EP=6 THEN CP=2
IF EP=7 THEN CP=1
IF TP=4 THEN DP=0
IF TP=5 THEN DP=3
IF TP=6 THEN DP=2
IF TP=7 THEN DP=1
NU = (DP - CP + 4) MOD 4
IF NU=1 THEN MS$="U": GOSUB DoMoves
IF NU=2 THEN MS$="UU": GOSUB DoMoves
IF NU=3 THEN MS$="u": GOSUB DoMoves
RETURN
REM
REM ==========================================
REM  EDGE INSERTION
REM ==========================================
REM
InsertAligned:
REM NO LOCAL VARS — ONLY SETS MS$ FOR DOMOVES
REM EDGE ABOVE TARGET WITH BOTTOM COLOR ON TOP (EO=0)
REM DOUBLE-TURN TARGET FACE
IF TI=0 THEN MS$="FF": GOSUB DoMoves
IF TI=1 THEN MS$="RR": GOSUB DoMoves
IF TI=2 THEN MS$="BB": GOSUB DoMoves
IF TI=3 THEN MS$="LL": GOSUB DoMoves
RETURN
REM
InsertFlipped:
REM NO LOCAL VARS — ONLY SETS MS$ FOR DOMOVES
REM EDGE ABOVE TARGET WITH BOTTOM COLOR ON SIDE (EO=1)
REM 3-MOVE: u + CW-ADJACENT + TARGET FACE
IF TI=0 THEN MS$="rF": GOSUB DoMoves
IF TI=1 THEN MS$="Br": GOSUB DoMoves
IF TI=2 THEN MS$="lB": GOSUB DoMoves
IF TI=3 THEN MS$="Fl": GOSUB DoMoves
RETURN
REM
REM ==========================================
REM  VERIFICATION
REM ==========================================
REM
CheckBottomCross:
LOCAL OK
OK = 1
IF CL(1,2,0,5)<>7 OR CL(1,2,0,0)<>4 THEN OK=0
IF CL(2,2,1,5)<>7 OR CL(2,2,1,2)<>3 THEN OK=0
IF CL(1,2,2,5)<>7 OR CL(1,2,2,1)<>5 THEN OK=0
IF CL(0,2,1,5)<>7 OR CL(0,2,1,3)<>6 THEN OK=0
IF OK=1 THEN PRINT "CROSS OK!" ELSE PRINT "CROSS FAIL!": STOP
RETURN
REM
REM ==========================================
REM  STEP 2: BOTTOM CORNERS
REM ==========================================
REM
SolveBottomCorners:
PRINT "STEP 2: BOTTOM CORNERS"
ST$="STEP 2: BOTTOM CORNERS": S2$=""
LOCAL RI, XOK
TC1 = 7
FOR RI = 1 TO 6
  TC2=4: TC3=3: CI=0: PRINT "  BFR CORNER": S2$="BFR CORNER  ": GOSUB SolveBotCorner
  TC2=4: TC3=6: CI=1: PRINT "  BFL CORNER": S2$="BFL CORNER  ": GOSUB SolveBotCorner
  TC2=5: TC3=3: CI=2: PRINT "  BBR CORNER": S2$="BBR CORNER  ": GOSUB SolveBotCorner
  TC2=5: TC3=6: CI=3: PRINT "  BBL CORNER": S2$="BBL CORNER  ": GOSUB SolveBotCorner
  REM CHECK IF ALL 4 SOLVED
  XOK = 1
  IF CL(2,2,0,5)<>7 OR CL(2,2,0,0)<>4 OR CL(2,2,0,2)<>3 THEN XOK=0
  IF CL(0,2,0,5)<>7 OR CL(0,2,0,0)<>4 OR CL(0,2,0,3)<>6 THEN XOK=0
  IF CL(2,2,2,5)<>7 OR CL(2,2,2,1)<>5 OR CL(2,2,2,2)<>3 THEN XOK=0
  IF CL(0,2,2,5)<>7 OR CL(0,2,2,1)<>5 OR CL(0,2,2,3)<>6 THEN XOK=0
  IF XOK=1 THEN RETURN
NEXT RI
RETURN
REM
SolveBotCorner:
REM SOLVE ONE BOTTOM CORNER
REM INPUT: TC1, TC2, TC3 (TARGET COLORS), CI (CORNER INDEX 0-3)
LOCAL AT
FOR AT = 1 TO 6
  GOSUB FindCorner
  REM ALREADY SOLVED?
  IF CP=CI AND CO=0 THEN RETURN
  REM EXTRACT FROM BOTTOM IF NEEDED
  IF CP<=3 THEN PRINT "    EXTRACTING": GOSUB ExtractCorner
  REM RE-FIND AFTER EXTRACT
  GOSUB FindCorner
  REM ALIGN ABOVE TARGET SLOT
  PRINT "    ALIGNING"
  GOSUB AlignCornerTop
  REM RE-FIND FOR CURRENT ORIENTATION
  GOSUB FindCorner
  REM INSERT
  PRINT "    INSERTING"
  GOSUB InsertCorner
  REM CHECK IF SOLVED
  GOSUB FindCorner
  IF CP=CI AND CO=0 THEN RETURN
NEXT AT
RETURN
REM
REM ==========================================
REM  CORNER EXTRACTION
REM ==========================================
REM
ExtractCorner:
REM NO LOCAL VARS — ONLY SETS MS$ FOR DOMOVES
REM EXTRACT CORNER FROM BOTTOM (CP 0-3) TO TOP
REM USES CURRENT SLOT'S EXTRACTION ALGORITHM
IF CP=0 THEN MS$="Rur": GOSUB DoMoves
IF CP=1 THEN MS$="FUf": GOSUB DoMoves
IF CP=2 THEN MS$="BUb": GOSUB DoMoves
IF CP=3 THEN MS$="Lul": GOSUB DoMoves
RETURN
REM
REM ==========================================
REM  CORNER ALIGNMENT
REM ==========================================
REM
AlignCornerTop:
REM ROTATE U TO POSITION CORNER ABOVE TARGET SLOT
REM TARGET TOP POSITION: CI+4
REM U CW CYCLE: 4(TFR)->5(TFL)->7(TBL)->6(TBR)->4
LOCAL TP, NU, CY, DY
TP = CI + 4
IF CP=TP THEN RETURN
REM CYCLE POSITIONS: 4=0, 5=1, 6=3, 7=2
IF CP=4 THEN CY=0
IF CP=5 THEN CY=1
IF CP=6 THEN CY=3
IF CP=7 THEN CY=2
IF TP=4 THEN DY=0
IF TP=5 THEN DY=1
IF TP=6 THEN DY=3
IF TP=7 THEN DY=2
NU = (DY - CY + 4) MOD 4
IF NU=1 THEN MS$="U": GOSUB DoMoves
IF NU=2 THEN MS$="UU": GOSUB DoMoves
IF NU=3 THEN MS$="u": GOSUB DoMoves
RETURN
REM
REM ==========================================
REM  CORNER INSERTION
REM ==========================================
REM
InsertCorner:
REM NO LOCAL VARS — DISPATCHES TO INSERT HELPERS
REM INSERT CORNER FROM TOP INTO TARGET SLOT
REM DISPATCH ON CI (TARGET) AND CO (ORIENTATION)
IF CI=0 THEN GOSUB InsertBFR
IF CI=1 THEN GOSUB InsertBFL
IF CI=2 THEN GOSUB InsertBBR
IF CI=3 THEN GOSUB InsertBBL
RETURN
REM
InsertBFR:
REM NO LOCAL VARS — ONLY SETS MS$ FOR DOMOVES
REM CO=2 (X-FACE) -> RUr, CO=1 (Z-FACE) -> fuF, CO=0 -> fuF
IF CO=2 THEN MS$="RUr": GOSUB DoMoves: RETURN
MS$="fuF": GOSUB DoMoves
RETURN
REM
InsertBFL:
REM NO LOCAL VARS — ONLY SETS MS$ FOR DOMOVES
REM CO=2 (X-FACE) -> luL, CO=1/0 -> FUf (luL has CO=1 fixed point)
IF CO=2 THEN MS$="luL": GOSUB DoMoves: RETURN
MS$="FUf": GOSUB DoMoves
RETURN
REM
InsertBBR:
REM NO LOCAL VARS — ONLY SETS MS$ FOR DOMOVES
REM CO=1 (Z-FACE) -> BUb, CO=2 (X-FACE) -> ruR, CO=0 -> BUb
IF CO=2 THEN MS$="ruR": GOSUB DoMoves: RETURN
MS$="BUb": GOSUB DoMoves
RETURN
REM
InsertBBL:
REM NO LOCAL VARS — ONLY SETS MS$ FOR DOMOVES
REM CO=2 (X-FACE) -> LUl, CO=1 (Z-FACE) -> buB, CO=0 -> buB
IF CO=2 THEN MS$="LUl": GOSUB DoMoves: RETURN
MS$="buB": GOSUB DoMoves
RETURN
REM
REM ==========================================
REM  CORNER VERIFICATION
REM ==========================================
REM
CheckBottomCorners:
LOCAL OK
OK = 1
IF CL(2,2,0,5)<>7 OR CL(2,2,0,0)<>4 OR CL(2,2,0,2)<>3 THEN OK=0
IF CL(0,2,0,5)<>7 OR CL(0,2,0,0)<>4 OR CL(0,2,0,3)<>6 THEN OK=0
IF CL(2,2,2,5)<>7 OR CL(2,2,2,1)<>5 OR CL(2,2,2,2)<>3 THEN OK=0
IF CL(0,2,2,5)<>7 OR CL(0,2,2,1)<>5 OR CL(0,2,2,3)<>6 THEN OK=0
IF OK=1 THEN PRINT "CORNERS OK!" ELSE PRINT "CORNERS FAIL!": STOP
RETURN
REM
REM ==========================================
REM  STEP 3: MIDDLE LAYER EDGES
REM ==========================================
REM
SolveMiddleEdges:
PRINT "STEP 3: MIDDLE EDGES"
ST$="STEP 3: MIDDLE EDGES": S2$=""
LOCAL RI, XOK
FOR RI = 1 TO 6
  TC1=4: TC2=3: EI=0: PRINT "  FR EDGE": S2$="FR EDGE  ": GOSUB SolveMidEdge
  TC1=4: TC2=6: EI=1: PRINT "  FL EDGE": S2$="FL EDGE  ": GOSUB SolveMidEdge
  TC1=5: TC2=3: EI=2: PRINT "  BR EDGE": S2$="BR EDGE  ": GOSUB SolveMidEdge
  TC1=5: TC2=6: EI=3: PRINT "  BL EDGE": S2$="BL EDGE  ": GOSUB SolveMidEdge
  REM CHECK IF ALL 4 SOLVED
  XOK = 1
  IF CL(2,1,0,0)<>4 OR CL(2,1,0,2)<>3 THEN XOK=0
  IF CL(0,1,0,0)<>4 OR CL(0,1,0,3)<>6 THEN XOK=0
  IF CL(2,1,2,1)<>5 OR CL(2,1,2,2)<>3 THEN XOK=0
  IF CL(0,1,2,1)<>5 OR CL(0,1,2,3)<>6 THEN XOK=0
  IF XOK=1 THEN RETURN
NEXT RI
RETURN
REM
SolveMidEdge:
REM SOLVE ONE MIDDLE EDGE
REM INPUT: TC1, TC2 (TARGET COLORS), EI (EDGE INDEX 0-3)
LOCAL AT
FOR AT = 1 TO 6
  GOSUB FindEdge
  REM ALREADY SOLVED? TARGET EP = EI+8
  IF EP=EI+8 AND EO=0 THEN RETURN
  REM IF IN MIDDLE BUT WRONG, EXTRACT TO TOP
  IF EP>=8 AND EP<=11 THEN PRINT "    EXTRACTING": GOSUB ExtractMidEdge
  REM RE-FIND (NOW IN TOP LAYER)
  GOSUB FindEdge
  REM ALIGN U UNTIL SIDE STICKER MATCHES CENTER
  PRINT "    ALIGNING"
  GOSUB AlignMidEdge
  REM RE-FIND FOR CURRENT POSITION
  GOSUB FindEdge
  REM INSERT
  PRINT "    INSERTING"
  GOSUB InsertMidEdge
  REM CHECK IF SOLVED
  GOSUB FindEdge
  IF EP=EI+8 AND EO=0 THEN RETURN
NEXT AT
RETURN
REM
REM ==========================================
REM  MIDDLE EDGE EXTRACTION
REM ==========================================
REM
ExtractMidEdge:
REM NO LOCAL VARS — ONLY SETS MS$ FOR DOMOVES
REM EXTRACT EDGE FROM MIDDLE (EP 8-11) TO TOP
REM USES ONE OF THE INSERT ALGORITHMS FOR THAT SLOT
IF EP=8 THEN MS$="URurufUF": GOSUB DoMoves
IF EP=9 THEN MS$="ulULUFuf": GOSUB DoMoves
IF EP=10 THEN MS$="urURUBub": GOSUB DoMoves
IF EP=11 THEN MS$="ULulubUB": GOSUB DoMoves
RETURN
REM
REM ==========================================
REM  MIDDLE EDGE ALIGNMENT
REM ==========================================
REM
AlignMidEdge:
REM ROTATE U UNTIL SIDE STICKER MATCHES CENTER
REM SIDE STICKER COLOR: EO=0 -> TC2, EO=1 -> TC1
REM SIDE FACE CENTERS: FRONT=4, RIGHT=3, BACK=5, LEFT=6
LOCAL SC, TP, NU, CP, DP
IF EO=0 THEN SC=TC2 ELSE SC=TC1
REM TARGET EP WHERE SIDE COLOR MATCHES CENTER
IF SC=4 THEN TP=4
IF SC=3 THEN TP=5
IF SC=5 THEN TP=6
IF SC=6 THEN TP=7
IF EP=TP THEN RETURN
REM COMPUTE U TURNS USING EDGE CYCLE
REM U CW CYCLE: 4(FRONT)->7(LEFT)->6(BACK)->5(RIGHT)->4
IF EP=4 THEN CP=0
IF EP=5 THEN CP=3
IF EP=6 THEN CP=2
IF EP=7 THEN CP=1
IF TP=4 THEN DP=0
IF TP=5 THEN DP=3
IF TP=6 THEN DP=2
IF TP=7 THEN DP=1
NU = (DP - CP + 4) MOD 4
IF NU=1 THEN MS$="U": GOSUB DoMoves
IF NU=2 THEN MS$="UU": GOSUB DoMoves
IF NU=3 THEN MS$="u": GOSUB DoMoves
RETURN
REM
REM ==========================================
REM  MIDDLE EDGE INSERTION
REM ==========================================
REM
InsertMidEdge:
REM NO LOCAL VARS — DISPATCHES ON EI AND EP
REM EP AFTER ALIGNMENT TELLS US WHICH FACE THE SIDE STICKER IS ON
REM EP=4: SIDE ON FRONT, EP=5: SIDE ON RIGHT
REM EP=6: SIDE ON BACK, EP=7: SIDE ON LEFT
IF EI=0 THEN GOSUB InsertFR
IF EI=1 THEN GOSUB InsertFL
IF EI=2 THEN GOSUB InsertBR
IF EI=3 THEN GOSUB InsertBL
RETURN
REM
InsertFR:
REM NO LOCAL VARS — ONLY SETS MS$ FOR DOMOVES
REM SIDE ON FRONT (EP=4): INSERT TOWARD RIGHT
IF EP=4 THEN MS$="URurufUF": GOSUB DoMoves: RETURN
REM SIDE ON RIGHT (EP=5): INSERT TOWARD FRONT
MS$="ufUFURur": GOSUB DoMoves
RETURN
REM
InsertFL:
REM NO LOCAL VARS — ONLY SETS MS$ FOR DOMOVES
REM SIDE ON FRONT (EP=4): INSERT TOWARD LEFT
IF EP=4 THEN MS$="ulULUFuf": GOSUB DoMoves: RETURN
REM SIDE ON LEFT (EP=7): INSERT TOWARD FRONT
MS$="UFufulUL": GOSUB DoMoves
RETURN
REM
InsertBR:
REM NO LOCAL VARS — ONLY SETS MS$ FOR DOMOVES
REM SIDE ON BACK (EP=6): INSERT TOWARD RIGHT
IF EP=6 THEN MS$="urURUBub": GOSUB DoMoves: RETURN
REM SIDE ON RIGHT (EP=5): INSERT TOWARD BACK
MS$="UBuburUR": GOSUB DoMoves
RETURN
REM
InsertBL:
REM NO LOCAL VARS — ONLY SETS MS$ FOR DOMOVES
REM SIDE ON BACK (EP=6): INSERT TOWARD LEFT
IF EP=6 THEN MS$="ULulubUB": GOSUB DoMoves: RETURN
REM SIDE ON LEFT (EP=7): INSERT TOWARD BACK
MS$="ubUBULul": GOSUB DoMoves
RETURN
REM
REM ==========================================
REM  MIDDLE EDGE VERIFICATION
REM ==========================================
REM
CheckMiddleEdges:
LOCAL OK
OK = 1
IF CL(2,1,0,0)<>4 OR CL(2,1,0,2)<>3 THEN OK=0
IF CL(0,1,0,0)<>4 OR CL(0,1,0,3)<>6 THEN OK=0
IF CL(2,1,2,1)<>5 OR CL(2,1,2,2)<>3 THEN OK=0
IF CL(0,1,2,1)<>5 OR CL(0,1,2,3)<>6 THEN OK=0
IF OK=1 THEN PRINT "MIDDLE OK!" ELSE PRINT "MIDDLE FAIL!": STOP
RETURN
REM
REM ==========================================
REM  STEP 4: TOP CROSS (OLL EDGES)
REM ==========================================
REM
SolveTopCross:
PRINT "STEP 4: TOP CROSS"
ST$="STEP 4: TOP CROSS": S2$=""
LOCAL IT
FOR IT = 1 TO 4
  REM COUNT YELLOW TOP EDGES
  GOSUB CountTopYellow
  IF YC=4 THEN RETURN
  REM ERROR ON IMPOSSIBLE COUNTS
  IF YC=1 OR YC=3 THEN PRINT "ERROR: YC=";YC: STOP
  REM DOT (YC=0): APPLY DIRECTLY
  IF YC=0 THEN PRINT "  DOT->L": S2$="DOT->L  ": MS$="FRUruf": GOSUB DoMoves: GOTO TopCrossNext
  REM YC=2: DISTINGUISH L-SHAPE FROM LINE
  GOSUB ClassifyTopEdges
  IF TP$="L" THEN GOSUB OrientLShape: PRINT "  L->LINE": S2$="L->LINE  ": MS$="FRUruf": GOSUB DoMoves: GOTO TopCrossNext
  IF TP$="I" THEN GOSUB OrientLine: PRINT "  LINE->CROSS": S2$="LINE->CROSS  ": MS$="FRUruf": GOSUB DoMoves: GOTO TopCrossNext
  TopCrossNext:
NEXT IT
PRINT "ERROR: TOP CROSS NOT SOLVED AFTER 4 ITERATIONS": STOP
RETURN
REM
CountTopYellow:
REM COUNT HOW MANY TOP EDGES SHOW YELLOW (2)
REM OUTPUT: YC (0-4)
YC=0
IF CL(1,0,0,4)=2 THEN YC=YC+1
IF CL(2,0,1,4)=2 THEN YC=YC+1
IF CL(1,0,2,4)=2 THEN YC=YC+1
IF CL(0,0,1,4)=2 THEN YC=YC+1
RETURN
REM
ClassifyTopEdges:
REM CLASSIFY YC=2 PATTERN AS L-SHAPE OR LINE
REM OUTPUT: TP$ = "L" (ADJACENT) OR "I" (OPPOSITE)
REM CHECK FOR OPPOSITE PAIRS (LINE)
IF CL(1,0,0,4)=2 AND CL(1,0,2,4)=2 THEN TP$="I": RETURN
IF CL(2,0,1,4)=2 AND CL(0,0,1,4)=2 THEN TP$="I": RETURN
REM OTHERWISE ADJACENT (L-SHAPE)
TP$="L"
RETURN
REM
OrientLShape:
REM ROTATE U UNTIL YELLOW EDGES ARE AT BACK AND LEFT
LOCAL J
FOR J=1 TO 4
  IF CL(1,0,2,4)=2 AND CL(0,0,1,4)=2 THEN RETURN
  MS$="U": GOSUB DoMoves
NEXT J
RETURN
REM
OrientLine:
REM ROTATE U UNTIL YELLOW EDGES ARE AT LEFT AND RIGHT
LOCAL J
FOR J=1 TO 4
  IF CL(2,0,1,4)=2 AND CL(0,0,1,4)=2 THEN RETURN
  MS$="U": GOSUB DoMoves
NEXT J
RETURN
REM
REM ==========================================
REM  TOP CROSS VERIFICATION
REM ==========================================
REM
CheckTopCross:
LOCAL OK
OK = 1
IF CL(1,0,0,4)<>2 THEN OK=0
IF CL(2,0,1,4)<>2 THEN OK=0
IF CL(1,0,2,4)<>2 THEN OK=0
IF CL(0,0,1,4)<>2 THEN OK=0
IF OK=1 THEN PRINT "TOP CROSS OK!" ELSE PRINT "TOP CROSS FAIL!": STOP
RETURN
