REM === RUBIK'S CUBE SOLVER LIBRARY ===
REM BEGINNER'S LAYER-BY-LAYER METHOD
REM MERGE THIS FILE — REQUIRES lib_rubiks_engine
REM
REM ==========================================
REM  STEP 1: BOTTOM CROSS
REM ==========================================
REM
SolveBottomCross:
REM SOLVE 4 BOTTOM EDGES: FRONT, RIGHT, BACK, LEFT
REM RETRY LOOP HANDLES CASES WHERE INSERTING
REM THE LAST EDGE DISTURBS AN EARLIER ONE
LOCAL SC, XOK
TC1 = 7: REM MAGENTA (BOTTOM COLOR)
FOR SC = 1 TO 3
  TC2 = 4: TI = 0: GOSUB SolveBotEdge
  TC2 = 3: TI = 1: GOSUB SolveBotEdge
  TC2 = 5: TI = 2: GOSUB SolveBotEdge
  TC2 = 6: TI = 3: GOSUB SolveBotEdge
  REM CHECK IF ALL 4 SOLVED
  XOK = 1
  IF CL(1,2,0,5)<>7 OR CL(1,2,0,0)<>4 THEN XOK=0
  IF CL(2,2,1,5)<>7 OR CL(2,2,1,2)<>3 THEN XOK=0
  IF CL(1,2,2,5)<>7 OR CL(1,2,2,1)<>5 THEN XOK=0
  IF CL(0,2,1,5)<>7 OR CL(0,2,1,3)<>6 THEN XOK=0
  IF XOK=1 THEN RETURN
NEXT SC
RETURN
REM
SolveBotEdge:
REM SOLVE ONE BOTTOM EDGE
REM INPUT: TC1, TC2 (TARGET COLORS), TI (TARGET INDEX 0-3)
LOCAL AT
FOR AT = 1 TO 6
  GOSUB FindEdge
  REM ALREADY SOLVED?
  IF EP=TI AND EO=0 THEN RETURN
  REM KICK FROM BOTTOM TO TOP
  IF EP<=3 THEN GOSUB KickBottom
  REM KICK FROM MIDDLE TO TOP
  IF EP>=8 THEN GOSUB KickMiddle
  REM RE-FIND AFTER KICK
  GOSUB FindEdge
  REM ALIGN ABOVE TARGET SLOT
  GOSUB AlignTop
  REM RE-FIND FOR CURRENT ORIENTATION
  GOSUB FindEdge
  REM INSERT BASED ON ORIENTATION
  IF EO=0 THEN GOSUB InsertAligned
  IF EO=1 THEN GOSUB InsertFlipped
  REM CHECK IF SOLVED
  GOSUB FindEdge
  IF EP=TI AND EO=0 THEN RETURN
NEXT AT
RETURN
REM
REM ==========================================
REM  EDGE FINDING
REM ==========================================
REM
FindEdge:
REM SEARCH ALL 12 EDGES FOR TARGET COLORS TC1, TC2
REM OUTPUT: EP (0-11 POSITION), EO (0=ALIGNED, 1=FLIPPED)
REM 0-3: BOTTOM EDGES (FACE-A=F5, FACE-B=SIDE)
GOSUB FE0: IF EP>=0 THEN RETURN
GOSUB FE1: IF EP>=0 THEN RETURN
GOSUB FE2: IF EP>=0 THEN RETURN
GOSUB FE3: IF EP>=0 THEN RETURN
REM 4-7: TOP EDGES (FACE-A=F4, FACE-B=SIDE)
GOSUB FE4: IF EP>=0 THEN RETURN
GOSUB FE5: IF EP>=0 THEN RETURN
GOSUB FE6: IF EP>=0 THEN RETURN
GOSUB FE7: IF EP>=0 THEN RETURN
REM 8-11: MIDDLE EDGES (SIDE + SIDE)
GOSUB FE8: IF EP>=0 THEN RETURN
GOSUB FE9: IF EP>=0 THEN RETURN
GOSUB FE10: IF EP>=0 THEN RETURN
GOSUB FE11: IF EP>=0 THEN RETURN
EP=-1: EO=-1
RETURN
REM
FE0:
EP=-1: CA=CL(1,2,0,5): CB=CL(1,2,0,0)
IF CA=TC1 AND CB=TC2 THEN EP=0: EO=0
IF CA=TC2 AND CB=TC1 THEN EP=0: EO=1
RETURN
FE1:
EP=-1: CA=CL(2,2,1,5): CB=CL(2,2,1,2)
IF CA=TC1 AND CB=TC2 THEN EP=1: EO=0
IF CA=TC2 AND CB=TC1 THEN EP=1: EO=1
RETURN
FE2:
EP=-1: CA=CL(1,2,2,5): CB=CL(1,2,2,1)
IF CA=TC1 AND CB=TC2 THEN EP=2: EO=0
IF CA=TC2 AND CB=TC1 THEN EP=2: EO=1
RETURN
FE3:
EP=-1: CA=CL(0,2,1,5): CB=CL(0,2,1,3)
IF CA=TC1 AND CB=TC2 THEN EP=3: EO=0
IF CA=TC2 AND CB=TC1 THEN EP=3: EO=1
RETURN
FE4:
EP=-1: CA=CL(1,0,0,4): CB=CL(1,0,0,0)
IF CA=TC1 AND CB=TC2 THEN EP=4: EO=0
IF CA=TC2 AND CB=TC1 THEN EP=4: EO=1
RETURN
FE5:
EP=-1: CA=CL(2,0,1,4): CB=CL(2,0,1,2)
IF CA=TC1 AND CB=TC2 THEN EP=5: EO=0
IF CA=TC2 AND CB=TC1 THEN EP=5: EO=1
RETURN
FE6:
EP=-1: CA=CL(1,0,2,4): CB=CL(1,0,2,1)
IF CA=TC1 AND CB=TC2 THEN EP=6: EO=0
IF CA=TC2 AND CB=TC1 THEN EP=6: EO=1
RETURN
FE7:
EP=-1: CA=CL(0,0,1,4): CB=CL(0,0,1,3)
IF CA=TC1 AND CB=TC2 THEN EP=7: EO=0
IF CA=TC2 AND CB=TC1 THEN EP=7: EO=1
RETURN
FE8:
EP=-1: CA=CL(2,1,0,0): CB=CL(2,1,0,2)
IF CA=TC1 AND CB=TC2 THEN EP=8: EO=0
IF CA=TC2 AND CB=TC1 THEN EP=8: EO=1
RETURN
FE9:
EP=-1: CA=CL(0,1,0,0): CB=CL(0,1,0,3)
IF CA=TC1 AND CB=TC2 THEN EP=9: EO=0
IF CA=TC2 AND CB=TC1 THEN EP=9: EO=1
RETURN
FE10:
EP=-1: CA=CL(2,1,2,1): CB=CL(2,1,2,2)
IF CA=TC1 AND CB=TC2 THEN EP=10: EO=0
IF CA=TC2 AND CB=TC1 THEN EP=10: EO=1
RETURN
FE11:
EP=-1: CA=CL(0,1,2,1): CB=CL(0,1,2,3)
IF CA=TC1 AND CB=TC2 THEN EP=11: EO=0
IF CA=TC2 AND CB=TC1 THEN EP=11: EO=1
RETURN
REM
REM ==========================================
REM  CORNER FINDING
REM ==========================================
REM
FindCorner:
REM SEARCH ALL 8 CORNERS FOR TARGET COLORS TC1, TC2, TC3
REM OUTPUT: CP (0-7 POSITION), CO (0-2 ORIENTATION)
REM CO=0: TC1 ON Y-FACE, CO=1: TC1 ON Z-FACE, CO=2: TC1 ON X-FACE
REM 0-3: BOTTOM CORNERS
GOSUB FC0: IF CP>=0 THEN RETURN
GOSUB FC1: IF CP>=0 THEN RETURN
GOSUB FC2: IF CP>=0 THEN RETURN
GOSUB FC3: IF CP>=0 THEN RETURN
REM 4-7: TOP CORNERS
GOSUB FC4: IF CP>=0 THEN RETURN
GOSUB FC5: IF CP>=0 THEN RETURN
GOSUB FC6: IF CP>=0 THEN RETURN
GOSUB FC7: IF CP>=0 THEN RETURN
CP=-1: CO=-1
RETURN
REM
FC0:
REM BFR (2,2,0): F5, F0, F2
CP=-1: CA=CL(2,2,0,5): CB=CL(2,2,0,0): CC=CL(2,2,0,2)
IF CA=TC1 AND ((CB=TC2 AND CC=TC3) OR (CB=TC3 AND CC=TC2)) THEN CP=0: CO=0
IF CB=TC1 AND ((CA=TC2 AND CC=TC3) OR (CA=TC3 AND CC=TC2)) THEN CP=0: CO=1
IF CC=TC1 AND ((CA=TC2 AND CB=TC3) OR (CA=TC3 AND CB=TC2)) THEN CP=0: CO=2
RETURN
FC1:
REM BFL (0,2,0): F5, F0, F3
CP=-1: CA=CL(0,2,0,5): CB=CL(0,2,0,0): CC=CL(0,2,0,3)
IF CA=TC1 AND ((CB=TC2 AND CC=TC3) OR (CB=TC3 AND CC=TC2)) THEN CP=1: CO=0
IF CB=TC1 AND ((CA=TC2 AND CC=TC3) OR (CA=TC3 AND CC=TC2)) THEN CP=1: CO=1
IF CC=TC1 AND ((CA=TC2 AND CB=TC3) OR (CA=TC3 AND CB=TC2)) THEN CP=1: CO=2
RETURN
FC2:
REM BBR (2,2,2): F5, F1, F2
CP=-1: CA=CL(2,2,2,5): CB=CL(2,2,2,1): CC=CL(2,2,2,2)
IF CA=TC1 AND ((CB=TC2 AND CC=TC3) OR (CB=TC3 AND CC=TC2)) THEN CP=2: CO=0
IF CB=TC1 AND ((CA=TC2 AND CC=TC3) OR (CA=TC3 AND CC=TC2)) THEN CP=2: CO=1
IF CC=TC1 AND ((CA=TC2 AND CB=TC3) OR (CA=TC3 AND CB=TC2)) THEN CP=2: CO=2
RETURN
FC3:
REM BBL (0,2,2): F5, F1, F3
CP=-1: CA=CL(0,2,2,5): CB=CL(0,2,2,1): CC=CL(0,2,2,3)
IF CA=TC1 AND ((CB=TC2 AND CC=TC3) OR (CB=TC3 AND CC=TC2)) THEN CP=3: CO=0
IF CB=TC1 AND ((CA=TC2 AND CC=TC3) OR (CA=TC3 AND CC=TC2)) THEN CP=3: CO=1
IF CC=TC1 AND ((CA=TC2 AND CB=TC3) OR (CA=TC3 AND CB=TC2)) THEN CP=3: CO=2
RETURN
FC4:
REM TFR (2,0,0): F4, F0, F2
CP=-1: CA=CL(2,0,0,4): CB=CL(2,0,0,0): CC=CL(2,0,0,2)
IF CA=TC1 AND ((CB=TC2 AND CC=TC3) OR (CB=TC3 AND CC=TC2)) THEN CP=4: CO=0
IF CB=TC1 AND ((CA=TC2 AND CC=TC3) OR (CA=TC3 AND CC=TC2)) THEN CP=4: CO=1
IF CC=TC1 AND ((CA=TC2 AND CB=TC3) OR (CA=TC3 AND CB=TC2)) THEN CP=4: CO=2
RETURN
FC5:
REM TFL (0,0,0): F4, F0, F3
CP=-1: CA=CL(0,0,0,4): CB=CL(0,0,0,0): CC=CL(0,0,0,3)
IF CA=TC1 AND ((CB=TC2 AND CC=TC3) OR (CB=TC3 AND CC=TC2)) THEN CP=5: CO=0
IF CB=TC1 AND ((CA=TC2 AND CC=TC3) OR (CA=TC3 AND CC=TC2)) THEN CP=5: CO=1
IF CC=TC1 AND ((CA=TC2 AND CB=TC3) OR (CA=TC3 AND CB=TC2)) THEN CP=5: CO=2
RETURN
FC6:
REM TBR (2,0,2): F4, F1, F2
CP=-1: CA=CL(2,0,2,4): CB=CL(2,0,2,1): CC=CL(2,0,2,2)
IF CA=TC1 AND ((CB=TC2 AND CC=TC3) OR (CB=TC3 AND CC=TC2)) THEN CP=6: CO=0
IF CB=TC1 AND ((CA=TC2 AND CC=TC3) OR (CA=TC3 AND CC=TC2)) THEN CP=6: CO=1
IF CC=TC1 AND ((CA=TC2 AND CB=TC3) OR (CA=TC3 AND CB=TC2)) THEN CP=6: CO=2
RETURN
FC7:
REM TBL (0,0,2): F4, F1, F3
CP=-1: CA=CL(0,0,2,4): CB=CL(0,0,2,1): CC=CL(0,0,2,3)
IF CA=TC1 AND ((CB=TC2 AND CC=TC3) OR (CB=TC3 AND CC=TC2)) THEN CP=7: CO=0
IF CB=TC1 AND ((CA=TC2 AND CC=TC3) OR (CA=TC3 AND CC=TC2)) THEN CP=7: CO=1
IF CC=TC1 AND ((CA=TC2 AND CB=TC3) OR (CA=TC3 AND CB=TC2)) THEN CP=7: CO=2
RETURN
REM
REM ==========================================
REM  KICK TO TOP LAYER
REM ==========================================
REM
KickBottom:
REM PIECE AT BOTTOM (EP=0..3), KICK TO TOP WITH DOUBLE-TURN
IF EP=0 THEN MS$="FF": GOSUB DoMoves
IF EP=1 THEN MS$="RR": GOSUB DoMoves
IF EP=2 THEN MS$="BB": GOSUB DoMoves
IF EP=3 THEN MS$="LL": GOSUB DoMoves
RETURN
REM
KickMiddle:
REM PIECE AT MIDDLE (EP=8..11), KICK TO TOP
REM CHOOSE FACE TURN THAT DOESN'T DISTURB SOLVED EDGES
REM EP=8  FRONT-RIGHT: f DISTURBS 0, r DISTURBS 1
REM EP=9  FRONT-LEFT:  F DISTURBS 0, L DISTURBS 3
REM EP=10 BACK-RIGHT:  B DISTURBS 2, R DISTURBS 1
REM EP=11 BACK-LEFT:   b DISTURBS 2, l DISTURBS 3
IF EP=8 THEN GOSUB KickMid8
IF EP=9 THEN GOSUB KickMid9
IF EP=10 THEN GOSUB KickMid10
IF EP=11 THEN GOSUB KickMid11
RETURN
REM
KickMid8:
REM FRONT-RIGHT: f DISTURBS 0, r DISTURBS 1
REM STUCK WHEN TI>=2 (BOTH 0,1 SOLVED)
IF TI>=2 THEN MS$="fUF": GOSUB DoMoves: RETURN
IF TI>=1 THEN MS$="r": GOSUB DoMoves: RETURN
MS$="f": GOSUB DoMoves
RETURN
REM
KickMid9:
REM FRONT-LEFT: F DISTURBS 0, L DISTURBS 3
REM NEVER STUCK (3 NOT SOLVED BEFORE 0)
IF TI>=1 THEN MS$="L": GOSUB DoMoves: RETURN
MS$="F": GOSUB DoMoves
RETURN
REM
KickMid10:
REM BACK-RIGHT: B DISTURBS 2, R DISTURBS 1
REM STUCK WHEN TI>=3 (BOTH 1,2 SOLVED)
IF TI>=3 THEN MS$="BUb": GOSUB DoMoves: RETURN
IF TI>=1 THEN MS$="R": GOSUB DoMoves: RETURN
MS$="B": GOSUB DoMoves
RETURN
REM
KickMid11:
REM BACK-LEFT: b DISTURBS 2, l DISTURBS 3
REM NEVER STUCK (3 NOT SOLVED BEFORE 2)
IF TI>=3 THEN MS$="l": GOSUB DoMoves: RETURN
MS$="b": GOSUB DoMoves
RETURN
REM
REM ==========================================
REM  TOP LAYER ALIGNMENT
REM ==========================================
REM
AlignTop:
REM ROTATE U TO POSITION EDGE ABOVE TARGET SLOT
REM TARGET TOP POSITION: TI+4
REM U CW CYCLE: 4(FRONT)->7(LEFT)->6(BACK)->5(RIGHT)->4
LOCAL TP, NU
TP = TI + 4
IF EP=TP THEN RETURN
REM ASSIGN CYCLE POSITIONS: 4=0, 7=1, 6=2, 5=3
IF EP=4 THEN CP=0
IF EP=5 THEN CP=3
IF EP=6 THEN CP=2
IF EP=7 THEN CP=1
IF TP=4 THEN DP=0
IF TP=5 THEN DP=3
IF TP=6 THEN DP=2
IF TP=7 THEN DP=1
NU = (DP - CP + 4) MOD 4
IF NU=1 THEN MS$="U": GOSUB DoMoves
IF NU=2 THEN MS$="UU": GOSUB DoMoves
IF NU=3 THEN MS$="u": GOSUB DoMoves
RETURN
REM
REM ==========================================
REM  EDGE INSERTION
REM ==========================================
REM
InsertAligned:
REM EDGE ABOVE TARGET WITH BOTTOM COLOR ON TOP (EO=0)
REM DOUBLE-TURN TARGET FACE
IF TI=0 THEN MS$="FF": GOSUB DoMoves
IF TI=1 THEN MS$="RR": GOSUB DoMoves
IF TI=2 THEN MS$="BB": GOSUB DoMoves
IF TI=3 THEN MS$="LL": GOSUB DoMoves
RETURN
REM
InsertFlipped:
REM EDGE ABOVE TARGET WITH BOTTOM COLOR ON SIDE (EO=1)
REM 3-MOVE: u + CW-ADJACENT + TARGET FACE
IF TI=0 THEN MS$="uRF": GOSUB DoMoves
IF TI=1 THEN MS$="uBR": GOSUB DoMoves
IF TI=2 THEN MS$="uLB": GOSUB DoMoves
IF TI=3 THEN MS$="uFL": GOSUB DoMoves
RETURN
REM
REM ==========================================
REM  VERIFICATION
REM ==========================================
REM
CheckBottomCross:
LOCAL OK
OK = 1
IF CL(1,2,0,5)<>7 OR CL(1,2,0,0)<>4 THEN OK=0
IF CL(2,2,1,5)<>7 OR CL(2,2,1,2)<>3 THEN OK=0
IF CL(1,2,2,5)<>7 OR CL(1,2,2,1)<>5 THEN OK=0
IF CL(0,2,1,5)<>7 OR CL(0,2,1,3)<>6 THEN OK=0
IF OK=1 THEN PRINT "CROSS OK!" ELSE PRINT "CROSS FAIL!": STOP
RETURN
REM
REM ==========================================
REM  STEP 2: BOTTOM CORNERS
REM ==========================================
REM
SolveBottomCorners:
PRINT "STEP 2: BOTTOM CORNERS"
LOCAL SC, XOK
TC1 = 7
FOR SC = 1 TO 6
  TC2=4: TC3=3: CI=0: PRINT "  BFR CORNER": GOSUB SolveBotCorner
  TC2=4: TC3=6: CI=1: PRINT "  BFL CORNER": GOSUB SolveBotCorner
  TC2=5: TC3=3: CI=2: PRINT "  BBR CORNER": GOSUB SolveBotCorner
  TC2=5: TC3=6: CI=3: PRINT "  BBL CORNER": GOSUB SolveBotCorner
  REM CHECK IF ALL 4 SOLVED
  XOK = 1
  IF CL(2,2,0,5)<>7 OR CL(2,2,0,0)<>4 OR CL(2,2,0,2)<>3 THEN XOK=0
  IF CL(0,2,0,5)<>7 OR CL(0,2,0,0)<>4 OR CL(0,2,0,3)<>6 THEN XOK=0
  IF CL(2,2,2,5)<>7 OR CL(2,2,2,1)<>5 OR CL(2,2,2,2)<>3 THEN XOK=0
  IF CL(0,2,2,5)<>7 OR CL(0,2,2,1)<>5 OR CL(0,2,2,3)<>6 THEN XOK=0
  IF XOK=1 THEN RETURN
NEXT SC
RETURN
REM
SolveBotCorner:
REM SOLVE ONE BOTTOM CORNER
REM INPUT: TC1, TC2, TC3 (TARGET COLORS), CI (CORNER INDEX 0-3)
LOCAL AT
FOR AT = 1 TO 6
  GOSUB FindCorner
  REM ALREADY SOLVED?
  IF CP=CI AND CO=0 THEN RETURN
  REM EXTRACT FROM BOTTOM IF NEEDED
  IF CP<=3 THEN PRINT "    EXTRACTING": GOSUB ExtractCorner
  REM RE-FIND AFTER EXTRACT
  GOSUB FindCorner
  REM ALIGN ABOVE TARGET SLOT
  PRINT "    ALIGNING"
  GOSUB AlignCornerTop
  REM RE-FIND FOR CURRENT ORIENTATION
  GOSUB FindCorner
  REM INSERT
  PRINT "    INSERTING"
  GOSUB InsertCorner
  REM CHECK IF SOLVED
  GOSUB FindCorner
  IF CP=CI AND CO=0 THEN RETURN
NEXT AT
RETURN
REM
REM ==========================================
REM  CORNER EXTRACTION
REM ==========================================
REM
ExtractCorner:
REM EXTRACT CORNER FROM BOTTOM (CP 0-3) TO TOP
REM USES CURRENT SLOT'S EXTRACTION ALGORITHM
IF CP=0 THEN MS$="ruR": GOSUB DoMoves
IF CP=1 THEN MS$="FUf": GOSUB DoMoves
IF CP=2 THEN MS$="BUb": GOSUB DoMoves
IF CP=3 THEN MS$="luL": GOSUB DoMoves
RETURN
REM
REM ==========================================
REM  CORNER ALIGNMENT
REM ==========================================
REM
AlignCornerTop:
REM ROTATE U TO POSITION CORNER ABOVE TARGET SLOT
REM TARGET TOP POSITION: CI+4
REM U CW CYCLE: 4(TFR)->5(TFL)->7(TBL)->6(TBR)->4
LOCAL TP, NU
TP = CI + 4
IF CP=TP THEN RETURN
REM CYCLE POSITIONS: 4=0, 5=1, 7=2, 6=3
IF CP=4 THEN CY=0
IF CP=5 THEN CY=1
IF CP=6 THEN CY=3
IF CP=7 THEN CY=2
IF TP=4 THEN DY=0
IF TP=5 THEN DY=1
IF TP=6 THEN DY=3
IF TP=7 THEN DY=2
NU = (DY - CY + 4) MOD 4
IF NU=1 THEN MS$="U": GOSUB DoMoves
IF NU=2 THEN MS$="UU": GOSUB DoMoves
IF NU=3 THEN MS$="u": GOSUB DoMoves
RETURN
REM
REM ==========================================
REM  CORNER INSERTION
REM ==========================================
REM
InsertCorner:
REM INSERT CORNER FROM TOP INTO TARGET SLOT
REM DISPATCH ON CI (TARGET) AND CO (ORIENTATION)
IF CI=0 THEN GOSUB InsertBFR
IF CI=1 THEN GOSUB InsertBFL
IF CI=2 THEN GOSUB InsertBBR
IF CI=3 THEN GOSUB InsertBBL
RETURN
REM
InsertBFR:
REM CO=2 (X-FACE) -> rUR, CO=1 (Z-FACE) -> fuF, CO=0 -> fuF
IF CO=2 THEN MS$="rUR": GOSUB DoMoves: RETURN
MS$="fuF": GOSUB DoMoves
RETURN
REM
InsertBFL:
REM CO=2 (X-FACE) -> Lul, CO=1/0 -> FUf (Lul has CO=1 fixed point)
IF CO=2 THEN MS$="Lul": GOSUB DoMoves: RETURN
MS$="FUf": GOSUB DoMoves
RETURN
REM
InsertBBR:
REM BUb (B U B') for all COs — Rur has CO fixed points
MS$="BUb": GOSUB DoMoves
RETURN
REM
InsertBBL:
REM CO=2 (X-FACE) -> lUL, CO=1 (Z-FACE) -> buB, CO=0 -> buB
IF CO=2 THEN MS$="lUL": GOSUB DoMoves: RETURN
MS$="buB": GOSUB DoMoves
RETURN
REM
REM ==========================================
REM  CORNER VERIFICATION
REM ==========================================
REM
CheckBottomCorners:
LOCAL OK
OK = 1
IF CL(2,2,0,5)<>7 OR CL(2,2,0,0)<>4 OR CL(2,2,0,2)<>3 THEN OK=0
IF CL(0,2,0,5)<>7 OR CL(0,2,0,0)<>4 OR CL(0,2,0,3)<>6 THEN OK=0
IF CL(2,2,2,5)<>7 OR CL(2,2,2,1)<>5 OR CL(2,2,2,2)<>3 THEN OK=0
IF CL(0,2,2,5)<>7 OR CL(0,2,2,1)<>5 OR CL(0,2,2,3)<>6 THEN OK=0
IF OK=1 THEN PRINT "CORNERS OK!" ELSE PRINT "CORNERS FAIL!": STOP
RETURN
