10 REM === RUBIK'S CUBE SOLVER ===
20 REM BEGINNER'S LAYER-BY-LAYER METHOD
30 SAFETY OFF
40 PMODE 4: SCREEN 1
50 MERGE "lib_rubiks_engine"
55 MERGE "lib_rubiks_solver"
60 GOSUB InitCube
65 ST$="RUBIK'S CUBE SOLVER": GOSUB ShowCube
68 PRINT "RUBIK'S CUBE SOLVER"
69 PRINT
70 REM --- SCRAMBLE (ANIMATED) ---
72 ST$="SCRAMBLING...": S2$=""
74 PRINT "SCRAMBLING..."
76 NM=20: GOSUB Scramble
78 PRINT "SCRAMBLED!": PRINT
80 ST$="SCRAMBLED!": GOSUB ShowCube
90 REM --- SOLVE (ANIMATED) ---
100 GOSUB SolveBottomCross
110 GOSUB CheckBottomCross
120 ST$="STEP 1 COMPLETE: BOTTOM CROSS": S2$="": GOSUB ShowCube
122 PRINT "STEP 1 COMPLETE: BOTTOM CROSS": PRINT
130 GOSUB SolveBottomCorners
140 GOSUB CheckBottomCorners
150 ST$="STEP 2 COMPLETE: BOTTOM CORNERS": S2$="": GOSUB ShowCube
152 PRINT "STEP 2 COMPLETE: BOTTOM CORNERS": PRINT
160 GOSUB SolveMiddleEdges
170 GOSUB CheckMiddleEdges
180 ST$="STEP 3 COMPLETE: MIDDLE EDGES": S2$="": GOSUB ShowCube
182 PRINT "STEP 3 COMPLETE: MIDDLE EDGES": PRINT
190 GOSUB SolveTopCross
200 GOSUB CheckTopCross
210 ST$="STEP 4 COMPLETE: TOP CROSS": S2$="": GOSUB ShowCube
212 PRINT "STEP 4 COMPLETE: TOP CROSS": PRINT
220 GOSUB SolveTopEdgeAlign
230 GOSUB CheckTopEdgeAlign
240 ST$="STEP 5 COMPLETE: TOP EDGES ALIGNED": S2$="": GOSUB ShowCube
242 PRINT "STEP 5 COMPLETE: TOP EDGES ALIGNED": PRINT
250 ST$="SOLVED THROUGH STEP 5!": GOSUB ShowCube
252 PRINT "SOLVED THROUGH STEP 5!"
260 END
